# Generated by Django 6.0.5 on 2026-05-21 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_page_seo_description_page_seo_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='contactinquiry',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['id']},
        ),
    ]
