# Generated by Django 6.0.5 on 2026-06-01 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_blogcategory_blogtag_brandlogo_faqcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='category',
        ),
        migrations.DeleteModel(
            name='PortfolioCategory',
        ),
        migrations.DeleteModel(
            name='PortfolioItem',
        ),
    ]
