# Generated by Django 6.0.5 on 2026-06-01 15:00

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_remove_portfolioitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Legacy content field', null=True),
        ),
        migrations.CreateModel(
            name='BlogContentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(choices=[('image_left', 'Image Left / Content Right'), ('image_right', 'Content Left / Image Right'), ('full_width', 'Full Width Content')], default='full_width', max_length=20)),
                ('heading', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/sections/')),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_sections', to='cms.blogpost')),
            ],
            options={
                'verbose_name': 'Blog Content Section',
                'ordering': ['order'],
            },
        ),
    ]
