# Generated by Django 6.0.5 on 2026-06-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_alter_blogpost_content_blogcontentsection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='List of features as JSON array'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Hero/thumbnail image for the service', null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show on website'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show on homepage'),
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Starting price per image', max_digits=8),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.CharField(blank=True, help_text='Brief description for service cards', max_length=300),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL identifier (auto-generated from title)', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Detailed service description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, help_text='Material icon name or emoji', max_length=100),
        ),
    ]
