# Generated by Django 6.0.5 on 2026-06-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_alter_service_options_service_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL identifier (auto-generated from title)', max_length=200, unique=True),
        ),
    ]
