# Generated by Django 6.0.5 on 2026-06-05 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_alter_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='hero_background',
            field=models.ImageField(blank=True, help_text='Hero section background image', null=True, upload_to='services/hero/'),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_subtitle',
            field=models.CharField(blank=True, help_text='Subtitle displayed in the hero section', max_length=300),
        ),
        migrations.CreateModel(
            name='ServiceContentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.CharField(choices=[('text_left', 'Text Left / Image Right'), ('text_right', 'Image Left / Text Right'), ('full_width', 'Full Width Content')], default='text_left', max_length=20)),
                ('heading', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/content/')),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_sections', to='cms.service')),
            ],
            options={
                'verbose_name': 'Service Content Section',
                'verbose_name_plural': 'Service Content Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='cms.service')),
            ],
            options={
                'verbose_name': 'Service Gallery Image',
                'verbose_name_plural': 'Service Gallery Images',
                'ordering': ['order'],
            },
        ),
    ]
