# Generated by Django 6.0.5 on 2026-06-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_service_hero_background_service_hero_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicegalleryimage',
            name='after_image',
            field=models.ImageField(blank=True, help_text='After image for before/after comparison', null=True, upload_to='services/gallery/before_after/'),
        ),
        migrations.AddField(
            model_name='servicegalleryimage',
            name='before_image',
            field=models.ImageField(blank=True, help_text='Before image for before/after comparison', null=True, upload_to='services/gallery/before_after/'),
        ),
        migrations.AddField(
            model_name='servicegalleryimage',
            name='category',
            field=models.CharField(blank=True, help_text='Filter category (e.g. "ecommerce", "fashion", "jewelry")', max_length=100),
        ),
        migrations.AddField(
            model_name='servicegalleryimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='servicegalleryimage',
            name='gallery_type',
            field=models.CharField(choices=[('before_after', 'Before & After'), ('portfolio', 'Portfolio'), ('case_study', 'Case Study')], default='portfolio', help_text='Gallery section type', max_length=20),
        ),
        migrations.AddField(
            model_name='servicegalleryimage',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show in featured showcase'),
        ),
        migrations.AddField(
            model_name='servicegalleryimage',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Display on website'),
        ),
        migrations.AlterField(
            model_name='servicegalleryimage',
            name='image',
            field=models.ImageField(help_text='Main portfolio/case-study image', upload_to='services/gallery/'),
        ),
    ]
