# Generated by Django 6.0.5 on 2026-06-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_servicegalleryimage_after_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Custom SEO meta description'),
        ),
        migrations.AddField(
            model_name='service',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Custom SEO title for this service page', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='show_in_footer',
            field=models.BooleanField(default=True, help_text='Show in footer services links'),
        ),
        migrations.AddField(
            model_name='service',
            name='show_in_mega_menu',
            field=models.BooleanField(default=True, help_text='Show in Solutions mega menu'),
        ),
        migrations.AddField(
            model_name='service',
            name='show_in_related',
            field=models.BooleanField(default=True, help_text='Show in related services section'),
        ),
        migrations.AddField(
            model_name='service',
            name='show_on_homepage',
            field=models.BooleanField(default=True, help_text='Show in homepage popular services section'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured service (highlighted on homepage)'),
        ),
    ]
