# Generated by Django 6.0.5 on 2026-06-05 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_service_seo_description_service_seo_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='hero_cta_link',
            field=models.CharField(blank=True, default='/free-trial', help_text='CTA button link in hero section', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_cta_text',
            field=models.CharField(blank=True, default='Start Free Trial', help_text='CTA button text in hero section', max_length=100),
        ),
        migrations.CreateModel(
            name='ServiceHeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/hero/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_images', to='cms.service')),
            ],
            options={
                'verbose_name': 'Service Hero Image',
                'verbose_name_plural': 'Service Hero Images',
                'ordering': ['order'],
            },
        ),
    ]
