# Generated by Django 6.0.6 on 2026-06-05 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_service_hero_cta_link_service_hero_cta_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Show on homepage')),
                ('tagline', models.CharField(blank=True, default='Photo Editing Services at Affordable Pricing', max_length=200)),
                ('title', models.CharField(default='Get pixel-perfect photo editing services with quality as our top priority', max_length=500)),
                ('description', models.TextField(blank=True, default='We edited over 5M+ images for brands, retailers, media agencies, and commercial photographers. Bulk order discounts available. Ready to assist 24/7.')),
                ('background_image', models.ImageField(blank=True, help_text='Hero section background image', null=True, upload_to='hero/')),
                ('cta_primary_text', models.CharField(blank=True, default='Free Trial', max_length=100)),
                ('cta_primary_link', models.CharField(blank=True, default='/free-trial', max_length=255)),
                ('cta_secondary_text', models.CharField(blank=True, default='See Pricing', max_length=100)),
                ('cta_secondary_link', models.CharField(blank=True, default='/pricing', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/slides/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('hero_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='cms.herosection')),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='e.g. "5M+"', max_length=50)),
                ('label', models.CharField(help_text='e.g. "Images Edited"', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('hero_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='cms.herosection')),
            ],
            options={
                'verbose_name': 'Hero Stat',
                'verbose_name_plural': 'Hero Stats',
                'ordering': ['order'],
            },
        ),
    ]
