# Generated by Django 6.0.5 on 2026-06-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_herosection_heroslide_herostat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_bio',
            field=models.TextField(blank=True, help_text='Short author biography for article footer'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Custom canonical URL if different from default'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='faq_schema',
            field=models.JSONField(blank=True, default=list, help_text='FAQPage structured data items: [{"question":"...","answer":"..."}]'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='Primary focus keyword for SEO', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Full-width hero image for article detail', null=True, upload_to='blog/hero/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_trending',
            field=models.BooleanField(default=False, help_text='Mark as trending/hot topic'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Custom SEO meta description'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Custom SEO title (overrides title)', max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_description',
            field=models.TextField(blank=True, help_text='Open Graph description'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph share image', null=True, upload_to='blog/og/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title', max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='reading_time',
            field=models.PositiveIntegerField(default=0, help_text='Estimated reading time in minutes'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='related_posts',
            field=models.ManyToManyField(blank=True, help_text='Manually related blog posts', to='cms.blogpost'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='related_services',
            field=models.ManyToManyField(blank=True, help_text='Related services to link', to='cms.service'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='Schedule future publication', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='secondary_keywords',
            field=models.JSONField(blank=True, default=list, help_text='Secondary keywords as JSON array'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='short_description',
            field=models.CharField(blank=True, help_text='SEO meta description / card description', max_length=300),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.CharField(blank=True, help_text='Article excerpt / summary', max_length=300),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show in featured section'),
        ),
    ]
