# Generated by Django 6.0.5 on 2026-06-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_enhance_blog_model_with_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='key_takeaways',
            field=models.JSONField(blank=True, default=list, help_text='Key takeaways / learning objectives as JSON array of strings'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='twitter_description',
            field=models.TextField(blank=True, help_text='Twitter Card description'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='twitter_image',
            field=models.ImageField(blank=True, help_text='Twitter Card share image', null=True, upload_to='blog/twitter/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='twitter_title',
            field=models.CharField(blank=True, help_text='Twitter Card title', max_length=200),
        ),
    ]
