# Generated by Django 6.0.5 on 2026-06-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_blogpost_key_takeaways_blogpost_twitter_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_blocks',
            field=models.JSONField(blank=True, default=list, help_text='Modular content blocks array. Supported types: heading, text, image, code, callout, faq, list, table, step, divider'),
        ),
    ]
