# Generated by Django 6.0.5 on 2026-06-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_blogpost_content_blocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Plan name (e.g. "Starter", "Professional")', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL identifier (auto-generated from title)', max_length=200, unique=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly price in USD', max_digits=8)),
                ('price_yearly', models.DecimalField(blank=True, decimal_places=2, help_text='Yearly price per month in USD (optional)', max_digits=8, null=True)),
                ('description', models.TextField(blank=True, help_text='Short description of the plan')),
                ('features', models.JSONField(blank=True, default=list, help_text='Feature list as JSON array of strings')),
                ('is_popular', models.BooleanField(default=False, help_text='Highlight as "Most Popular" plan')),
                ('button_text', models.CharField(blank=True, default='Get Started', help_text='CTA button text', max_length=100)),
                ('button_link', models.CharField(blank=True, default='/free-trial', help_text='CTA button link', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True, help_text='Show on website')),
            ],
            options={
                'verbose_name': 'Pricing Plan',
                'verbose_name_plural': 'Pricing Plans',
                'ordering': ['order'],
            },
        ),
    ]
