# Generated by Django 6.0.5 on 2026-06-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_pricingplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='content_blocks',
            field=models.JSONField(blank=True, default=list, help_text='Modular content blocks array. Supported types: heading, text, image, image_with_text, gallery, code, callout, faq, list, table, step, divider'),
        ),
    ]
