# Generated by Django 6.0.5 on 2026-06-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_service_content_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecontentsection',
            name='layout',
            field=models.CharField(choices=[('text_left', 'Text Left / Image Right'), ('text_right', 'Image Left / Text Right'), ('full_width', 'Full Width Content'), ('image_top', 'Image on Top / Text Below'), ('text_only', 'Text Only (No Image)')], default='text_left', max_length=20),
        ),
    ]
