# Generated by Django 6.0.5 on 2026-06-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_alter_servicecontentsection_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='client_role',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
