# Generated by Django 6.0.5 on 2026-06-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_testimonial_client_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontentsection',
            name='template',
            field=models.CharField(choices=[('image_left', 'Image Left / Content Right'), ('image_right', 'Content Left / Image Right'), ('full_width', 'Full Width Content'), ('image_top', 'Image Above / Text Below'), ('text_only', 'Text Only (No Image)')], default='full_width', max_length=20),
        ),
    ]
