# Generated by Django 6.0.5 on 2026-06-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_alter_blogpost_content_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='company',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
