# Generated by Django 6.0.5 on 2026-06-13 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_technology'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('bio', models.TextField(blank=True, help_text='Short author biography')),
                ('image', models.ImageField(blank=True, help_text='Author profile photo / avatar', null=True, upload_to='authors/')),
                ('image_alt', models.CharField(blank=True, help_text='Alt text for the author image', max_length=200)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_profile',
            field=models.ForeignKey(blank=True, help_text='Link to a registered author profile (provides avatar image)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='cms.author'),
        ),
    ]
