# Generated by Django 6.0.5 on 2026-06-14 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0025_author_blogpost_author_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfigSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Show this section on the homepage')),
                ('subtitle', models.CharField(blank=True, default='SIMPLE PRICING OF 3D CONTENT FOR E-COMMERCE', max_length=200)),
                ('title', models.CharField(default='Create your product detail page', max_length=500)),
                ('description', models.TextField(blank=True, default='Choose the pricing tier and card type that fits your product visualization needs.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Configurator Section',
                'verbose_name_plural': 'Pricing Configurator Section',
            },
        ),
        migrations.CreateModel(
            name='PricingConfigDropdownOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. "1-10 units"', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropdown_options', to='cms.pricingconfigsection')),
            ],
            options={
                'verbose_name': 'Dropdown Option',
                'verbose_name_plural': 'Dropdown Options',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PricingConfigCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_text', models.CharField(default='Continue', max_length=100)),
                ('url', models.CharField(default='/free-trial', max_length=500)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cta', to='cms.pricingconfigsection')),
            ],
            options={
                'verbose_name': 'CTA Button',
                'verbose_name_plural': 'CTA Buttons',
            },
        ),
        migrations.CreateModel(
            name='PricingConfigCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Card background / icon image', null=True, upload_to='pricing_config/')),
                ('title', models.CharField(max_length=200)),
                ('price', models.CharField(help_text='e.g. "$100"', max_length=50)),
                ('old_price', models.CharField(blank=True, help_text='Strikethrough old price, e.g. "$120"', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Short description for this card')),
                ('button_text', models.CharField(default='Select', max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cms.pricingconfigsection')),
            ],
            options={
                'verbose_name': 'Pricing Card',
                'verbose_name_plural': 'Pricing Cards',
                'ordering': ['sort_order'],
            },
        ),
    ]
