# Generated by Django 6.0.5 on 2026-06-14 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0026_pricingconfigsection_pricingconfigdropdownoption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingconfigcard',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='pricingconfigcard',
            name='price',
        ),
        migrations.CreateModel(
            name='PricingConfigCardPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(help_text='e.g. "$150"', max_length=50)),
                ('old_price', models.CharField(blank=True, help_text='Strikethrough price, e.g. "$180"', max_length=50)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='cms.pricingconfigcard')),
                ('unit_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_prices', to='cms.pricingconfigdropdownoption')),
            ],
            options={
                'verbose_name': 'Card Price by Unit Range',
                'verbose_name_plural': 'Card Prices by Unit Range',
                'ordering': ('unit_range__order',),
                'unique_together': {('card', 'unit_range')},
            },
        ),
    ]
