# Generated by Django 6.0.5 on 2026-06-14 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_pricing_card_price_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingconfigcardprice',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_prices', to='cms.pricingconfigsection'),
        ),
    ]
