# Generated by Django 6.0.5 on 2026-06-14 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0028_add_section_to_card_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AddField(
            model_name='author',
            name='designation',
            field=models.CharField(blank=True, help_text='Job title / designation', max_length=200),
        ),
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, help_text='Author email address (optional)', max_length=254),
        ),
        migrations.AddField(
            model_name='author',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook profile URL'),
        ),
        migrations.AddField(
            model_name='author',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL'),
        ),
        migrations.AddField(
            model_name='author',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show on website'),
        ),
        migrations.AddField(
            model_name='author',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL'),
        ),
        migrations.AddField(
            model_name='author',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Display order'),
        ),
        migrations.AddField(
            model_name='author',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='X / Twitter profile URL'),
        ),
        migrations.CreateModel(
            name='BlogDocumentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Document title', max_length=200)),
                ('file', models.FileField(help_text='Upload file (PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX)', upload_to='blog/documents/')),
                ('description', models.TextField(blank=True, help_text='Short description of the document')),
                ('download_text', models.CharField(default='Download Document', help_text='Download button text', max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_blocks', to='cms.blogpost')),
            ],
            options={
                'verbose_name': 'Document Block',
                'verbose_name_plural': 'Document Blocks',
                'ordering': ['sort_order'],
            },
        ),
    ]
