# Generated by Django 6.0.5 on 2026-06-14 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0029_author_enhancement_and_document_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='author_bio',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author_profile',
            field=models.ForeignKey(blank=True, help_text='Link to a registered author profile (provides avatar, bio, designation, social links)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='cms.author'),
        ),
    ]
