# Generated by Django 6.0.5 on 2026-06-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0030_remove_blogpost_author_author_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='image',
            field=models.ImageField(blank=True, help_text='Card image displayed next to pricing', null=True, upload_to='pricing/'),
        ),
    ]
