# Generated by Django 6.0.5 on 2026-06-15 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0031_pricingplan_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('product_name', models.CharField(max_length=300)),
                ('product_category', models.CharField(choices=[('clothing', 'Clothing / Apparel'), ('electronics', 'Electronics'), ('jewelry', 'Jewelry / Watches'), ('home_garden', 'Home & Garden'), ('beauty', 'Beauty / Cosmetics'), ('food', 'Food & Beverage'), ('automotive', 'Automotive'), ('other', 'Other')], max_length=50)),
                ('drive_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('project_requirements', models.TextField()),
                ('is_read', models.BooleanField(default=False, help_text='Mark as read when reviewed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Free Trial Submission',
                'verbose_name_plural': 'Free Trial Submissions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FreeTrialAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='free_trial_attachments/')),
                ('original_filename', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('free_trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cms.freetrial')),
            ],
            options={
                'verbose_name': 'Free Trial Attachment',
                'verbose_name_plural': 'Free Trial Attachments',
                'ordering': ('uploaded_at',),
            },
        ),
    ]
