# Generated by Django 6.0.5 on 2026-06-19 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0032_freetrial_freetrialattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended: 400×400px (1:1 square). Max 200KB. Author profile photo.', null=True, upload_to='authors/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='Recommended: 1920×1080px (16:9). Max 500KB. Used as homepage/top banner.', upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='blogcontentsection',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200×800px (3:2). Max 400KB. Inline blog content section image.', null=True, upload_to='blog/sections/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200×630px (1.91:1). Max 300KB. Blog listing card thumbnail.', null=True, upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1920×1080px (16:9). Max 500KB. Full-width hero for article detail.', null=True, upload_to='blog/hero/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200×630px (1.91:1). Max 300KB. Open Graph social share image.', null=True, upload_to='blog/og/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='twitter_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200×600px (2:1). Max 300KB. Twitter Card share image.', null=True, upload_to='blog/twitter/'),
        ),
        migrations.AlterField(
            model_name='brandlogo',
            name='logo',
            field=models.ImageField(help_text='Recommended: 300×150px, transparent PNG preferred. Max 100KB. Client/brand logo for trust bar.', upload_to='brands/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1920×1080px (16:9). Max 1MB. Homepage hero section background.', null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(help_text='Recommended: 1920×1080px (16:9). Max 500KB. Homepage hero slider slide.', upload_to='hero/slides/'),
        ),
        migrations.AlterField(
            model_name='pricingconfigcard',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended: 600×400px (3:2). Max 200KB. Pricing configurator card image.', null=True, upload_to='pricing_config/'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended: 600×400px (3:2). Max 200KB. Image displayed on pricing card.', null=True, upload_to='pricing/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='hero_background',
            field=models.ImageField(blank=True, help_text='Recommended: 1920×1080px (16:9). Max 1MB. Hero section background for service pages.', null=True, upload_to='services/hero/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended: 800×600px (4:3). Max 300KB. Used in service cards and mega menu.', null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='servicecontentsection',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200×800px (3:2). Max 400KB. Inline content section image.', null=True, upload_to='services/content/'),
        ),
        migrations.AlterField(
            model_name='servicegalleryimage',
            name='after_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200×900px (4:3). Max 500KB. Before/after comparison image.', null=True, upload_to='services/gallery/before_after/'),
        ),
        migrations.AlterField(
            model_name='servicegalleryimage',
            name='before_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200×900px (4:3). Max 500KB. Before/after comparison image.', null=True, upload_to='services/gallery/before_after/'),
        ),
        migrations.AlterField(
            model_name='servicegalleryimage',
            name='image',
            field=models.ImageField(help_text='Recommended: 1200×900px (4:3). Max 500KB. Main gallery/portfolio image for service.', upload_to='services/gallery/'),
        ),
        migrations.AlterField(
            model_name='serviceheroimage',
            name='image',
            field=models.ImageField(help_text='Recommended: 1920×1080px (16:9). Max 500KB. Hero slider image for service.', upload_to='services/hero/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, help_text='Recommended: 400×400px (1:1 square). Max 200KB. Team member profile photo.', null=True, upload_to='team/'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=models.ImageField(blank=True, help_text='Recommended: 200×200px, transparent PNG/SVG preferred. Max 100KB. Technology partner logo.', null=True, upload_to='technology/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Recommended: 200×200px (1:1 square). Max 100KB. Client testimonial avatar.', null=True, upload_to='testimonials/'),
        ),
    ]
