# Generated by Django 6.0.5 on 2026-06-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0033_alter_author_image_alter_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended: 400×400px (1:1 square). Format: JPG or WebP. Max 200KB. Author profile photo shown on blog posts and author pages.', null=True, upload_to='authors/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='Recommended: 1920×1080px (16:9 landscape). Format: JPG or WebP. Max 500KB. Used as homepage/top promotional banner.', upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='blogcontentsection',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200×800px (3:2). Format: JPG or WebP. Max 400KB. Inline content section image within blog articles.', null=True, upload_to='blog/sections/'),
        ),
        migrations.AlterField(
            model_name='blogdocumentblock',
            name='file',
            field=models.FileField(help_text='Accepted: PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX. Max 20MB per file. Used as downloadable document attachments on blog posts.', upload_to='blog/documents/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200×630px (1.91:1 landscape). Format: JPG or WebP. Max 300KB. Blog listing card thumbnail and featured image in blog previews.', null=True, upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1920×1080px (16:9 landscape). Format: JPG or WebP. Max 500KB. Full-width hero image at the top of blog article detail pages.', null=True, upload_to='blog/hero/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200×630px (1.91:1 landscape). Format: JPG or PNG. Max 300KB. Open Graph image used when the page is shared on Facebook, LinkedIn, and other social platforms.', null=True, upload_to='blog/og/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='twitter_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200×600px (2:1 landscape). Format: JPG or PNG. Max 300KB. Twitter Card image for large summary cards when shared on X/Twitter.', null=True, upload_to='blog/twitter/'),
        ),
        migrations.AlterField(
            model_name='brandlogo',
            name='logo',
            field=models.ImageField(help_text='Recommended: 300×150px. Format: transparent PNG or SVG preferred. Max 100KB. Client/brand logo displayed in the Trust Bar / brands carousel section.', upload_to='brands/'),
        ),
        migrations.AlterField(
            model_name='freetrialattachment',
            name='file',
            field=models.FileField(help_text='Max 20MB per file. Supported: JPG, PNG, PDF, DOC, DOCX, ZIP. Used as file attachments submitted with free trial requests. Clients upload reference files describing their project needs.', upload_to='free_trial_attachments/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1920×1080px (16:9 landscape). Format: JPG or WebP (high quality, wide banner). Max 1MB. Used as full-width homepage hero section background.', null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(help_text='Recommended: 1920×1080px (16:9 landscape). Format: JPG or WebP. Max 500KB. Used in homepage hero slider/carousel.', upload_to='hero/slides/'),
        ),
        migrations.AlterField(
            model_name='pricingconfigcard',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended: 600×400px (3:2). Format: JPG or WebP. Max 200KB. Image displayed on pricing configurator cards.', null=True, upload_to='pricing_config/'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended: 600×400px (3:2). Format: JPG or WebP. Max 200KB. Image displayed on pricing plan cards.', null=True, upload_to='pricing/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='hero_background',
            field=models.ImageField(blank=True, help_text='Recommended: 1920×1080px (16:9 landscape). Format: JPG or WebP. Max 1MB. Full-width hero section background on individual service pages.', null=True, upload_to='services/hero/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended: 800×600px (4:3). Format: JPG or WebP. Max 300KB. Used in service cards, mega menu, and homepage sections.', null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='servicecontentsection',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200×800px (3:2). Format: JPG or WebP. Max 400KB. Inline content section image within service detail pages.', null=True, upload_to='services/content/'),
        ),
        migrations.AlterField(
            model_name='servicegalleryimage',
            name='after_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200×900px (4:3). Format: JPG or PNG. Max 500KB. Before/after comparison images on service pages. Both images should match dimensions exactly.', null=True, upload_to='services/gallery/before_after/'),
        ),
        migrations.AlterField(
            model_name='servicegalleryimage',
            name='before_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200×900px (4:3). Format: JPG or PNG. Max 500KB. Before/after comparison images on service pages. Both images should match dimensions exactly.', null=True, upload_to='services/gallery/before_after/'),
        ),
        migrations.AlterField(
            model_name='servicegalleryimage',
            name='image',
            field=models.ImageField(help_text='Recommended: 1200×900px (4:3). Format: JPG or WebP. Max 500KB. Main gallery/portfolio image displayed on service detail pages.', upload_to='services/gallery/'),
        ),
        migrations.AlterField(
            model_name='serviceheroimage',
            name='image',
            field=models.ImageField(help_text='Recommended: 1920×1080px (16:9 landscape). Format: JPG or WebP. Max 500KB. Hero slider image for service detail pages.', upload_to='services/hero/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, help_text='Recommended: 400×400px (1:1 square). Format: JPG or WebP. Max 200KB. Team member profile photo displayed on the team/about page.', null=True, upload_to='team/'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=models.ImageField(blank=True, help_text='Recommended: 200×200px. Format: transparent PNG or SVG preferred. Max 100KB. Technology partner logo displayed in the expertise/technology section.', null=True, upload_to='technology/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Recommended: 200×200px (1:1 square). Format: JPG or PNG. Max 100KB. Client testimonial avatar. Face should be well-framed and centered.', null=True, upload_to='testimonials/'),
        ),
    ]
