# Generated by Django 6.0.5 on 2026-06-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0034_alter_author_image_alter_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(help_text='Recommended: 1920×1080px (16:9). Format: JPG or WebP. Max 1–2MB. Used in homepage hero slider. Use high-quality wide banner images.', upload_to='hero/slides/'),
        ),
        migrations.AlterField(
            model_name='servicecontentsection',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended: 800×800px (1:1 square). Format: JPG or WebP. Max 400KB. Used alongside service content blocks. Keep clean and minimal background.', null=True, upload_to='services/content/'),
        ),
        migrations.AlterField(
            model_name='servicegalleryimage',
            name='after_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200×800px (3:2). Format: JPG or PNG. Max 500KB. Upload paired images with same lighting and angle for accurate comparison slider.', null=True, upload_to='services/gallery/before_after/'),
        ),
        migrations.AlterField(
            model_name='servicegalleryimage',
            name='before_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200×800px (3:2). Format: JPG or PNG. Max 500KB. Upload paired images with same lighting and angle for accurate comparison slider.', null=True, upload_to='services/gallery/before_after/'),
        ),
        migrations.AlterField(
            model_name='servicegalleryimage',
            name='image',
            field=models.ImageField(help_text='Recommended: 1200×800px (3:2). Format: JPG or WebP. Max 500KB. Used in service detail gallery section. Ensure consistent lighting and quality.', upload_to='services/gallery/'),
        ),
        migrations.AlterField(
            model_name='serviceheroimage',
            name='image',
            field=models.ImageField(help_text='Recommended: 1600×900px (16:9). Format: JPG or WebP. Max 500KB. Used at top of service pages. Keep subject centered.', upload_to='services/hero/'),
        ),
    ]
