# Generated by Django 6.0.5 on 2026-06-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_alter_heroslide_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, help_text='Use professional portrait (1:1 square). Shown on blog posts and author profile pages. Rendered as a circular avatar next to the author byline. Keep face centered with good lighting. Minimum size: 400×400px.', null=True, upload_to='authors/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='Use wide landscape image (16:9 preferred). Shown as a full-width top banner on the homepage. Scales responsively — edges are cropped on narrow screens. Keep primary subject and text-safe area in the center 60%. Minimum width: 1920px.', upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='blogcontentsection',
            name='image',
            field=models.ImageField(blank=True, help_text='Use versatile composition (3:2 or 16:9). Inline image within blog article content. Full-width on mobile, contained within the article column on desktop. Always within the reading area, so extreme aspect ratios (very tall/wide) may look odd. Minimum width: 1200px.', null=True, upload_to='blog/sections/'),
        ),
        migrations.AlterField(
            model_name='blogdocumentblock',
            name='file',
            field=models.FileField(help_text='Downloadable document attachment for blog posts. Accepted formats: PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX. Maximum file size: 20MB. Linked as a download button within the article.', upload_to='blog/documents/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Use wide landscape composition (16:9 or 1.91:1). Thumbnail in blog listing cards and previews. Cards use a fixed aspect ratio container — image crops to fill. Keep title-relevant visuals in the center. Minimum width: 1200px.', null=True, upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Use wide landscape image (16:9). Full-width hero at the top of blog article pages. Scales to viewport width — edges crop on mobile. Article title overlays near the bottom, so leave clear space there. Minimum width: 1920px.', null=True, upload_to='blog/hero/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Use 1.91:1 landscape ratio (1200×630px output). This exact ratio is enforced by Facebook, LinkedIn, and Slack previews. The image will NOT be cropped — it fills a fixed social card area. Ensure text and branding fit within the center 80% to avoid clipping in chat/embed views. Minimum width: 1200px.', null=True, upload_to='blog/og/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='twitter_image',
            field=models.ImageField(blank=True, help_text='Use 2:1 landscape ratio (1200×600px output). This exact ratio is enforced by X/Twitter large summary cards. Image fills a fixed-width preview in the feed. Text and key visuals should stay in the center safe area. Minimum width: 1200px.', null=True, upload_to='blog/twitter/'),
        ),
        migrations.AlterField(
            model_name='brandlogo',
            name='logo',
            field=models.ImageField(help_text='Use transparent-background logo (PNG or SVG preferred). Displayed in the Trust Bar / brands carousel section. Logos render at various sizes depending on viewport — a vector SVG ensures crisp rendering everywhere. If using PNG, minimum width: 300px. Avoid embedded text that becomes illegible at small sizes.', upload_to='brands/'),
        ),
        migrations.AlterField(
            model_name='freetrialattachment',
            name='file',
            field=models.FileField(help_text='File attachment submitted with free trial requests. Clients upload reference images or documents describing their project needs. Accepted formats: JPG, PNG, PDF, DOC, DOCX, ZIP. Maximum file size: 20MB.', upload_to='free_trial_attachments/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Use high-resolution wide image (16:9 landscape). This is a full-width background that spans the entire viewport. Crops horizontally on mobile and tablets — keep all key content in the center 60% safe zone. Minimum width: 1920px. Text overlays may appear on top, so avoid busy patterns near center.', null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(help_text='Use high-resolution wide image (16:9 landscape). Displayed full-width in the homepage hero slider. Crops significantly on mobile — ensure subject remains visible within the center 50% safe zone. Minimum width: 1920px. Dark overlay may be applied for text readability.', upload_to='hero/slides/'),
        ),
        migrations.AlterField(
            model_name='pricingconfigcard',
            name='image',
            field=models.ImageField(blank=True, help_text='Use clean landscape composition (3:2). Displayed in the pricing configurator card grid. Cards are fixed-aspect containers — images crop to fill. Keep subject centered for consistent card appearance. Minimum width: 600px.', null=True, upload_to='pricing_config/'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='image',
            field=models.ImageField(blank=True, help_text='Use clean landscape composition (3:2). Displayed inside pricing plan cards. Cards are fixed-aspect-ratio containers — images crop to fit. Keep product/visual centered and avoid edge-dependent details. Minimum width: 600px.', null=True, upload_to='pricing/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='hero_background',
            field=models.ImageField(blank=True, help_text='Use wide landscape image (16:9). Full-width hero background on individual service pages. Scales to fill the viewport width on all devices. Content may overlay on top — use simple, uncluttered areas in the center. Crops vertically on tall screens. Minimum width: 1920px.', null=True, upload_to='services/hero/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Use consistent landscape composition (4:3). Displayed in service cards, mega menu, and homepage sections. Cards maintain a fixed aspect ratio — images are cropped to fill the container. Keep the focal point centered. Minimum width: 800px. Aim for consistent framing across all service thumbnails.', null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='servicecontentsection',
            name='image',
            field=models.ImageField(blank=True, help_text='Use square or near-square composition (1:1 or 4:5). This image appears beside text on desktop and stacks full-width below text on mobile. At desktop it occupies roughly 50% of the row; on mobile it stretches to full width. Keep subject centered — edges are more visible on mobile. Minimum width: 800px.', null=True, upload_to='services/content/'),
        ),
        migrations.AlterField(
            model_name='servicegalleryimage',
            name='after_image',
            field=models.ImageField(blank=True, help_text='CRITICAL: Both images must use IDENTICAL dimensions and aspect ratio. Use balanced landscape ratio (3:2 or 4:3). Shot must have the same framing, lighting, and perspective for an accurate comparison slider. The slider overlay reveals differences — identical composition is non-negotiable. Minimum width: 1200px.', null=True, upload_to='services/gallery/before_after/'),
        ),
        migrations.AlterField(
            model_name='servicegalleryimage',
            name='before_image',
            field=models.ImageField(blank=True, help_text='CRITICAL: Both images must use IDENTICAL dimensions and aspect ratio. Use balanced landscape ratio (3:2 or 4:3). Shot must have the same framing, lighting, and perspective for an accurate comparison slider. The slider overlay reveals differences — identical composition is non-negotiable. Minimum width: 1200px.', null=True, upload_to='services/gallery/before_after/'),
        ),
        migrations.AlterField(
            model_name='servicegalleryimage',
            name='image',
            field=models.ImageField(help_text='Use flexible composition (3:2 preferred). Displayed in a responsive image grid on service detail pages. Grid columns reduce from 3→2→1 on smaller screens. Images may be cropped or shown at native aspect ratio. Ensure consistent lighting and quality across the gallery set. Minimum width: 1200px.', upload_to='services/gallery/'),
        ),
        migrations.AlterField(
            model_name='serviceheroimage',
            name='image',
            field=models.ImageField(help_text='Use landscape image (16:9). Displayed at the top of service pages in a slider. Adapts responsively across desktop and mobile. Keep subject centered as edges may be cropped on small screens. Minimum width: 1600px.', upload_to='services/hero/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, help_text='Use professional headshot (1:1 square). Displayed in team member cards on the about/team page. Rendered as rounded or circular thumbnails. Frame the face in the center with shoulders visible. Minimum size: 400×400px.', null=True, upload_to='team/'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=models.ImageField(blank=True, help_text='Use transparent-background logo (SVG or PNG). Displayed in the technology/expertise partner grid. Icons render in a responsive grid that adjusts columns. SVG is strongly preferred for crisp rendering at any size. If PNG, minimum width: 200px. Keep proportions square-ish.', null=True, upload_to='technology/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Use close-cropped portrait (1:1 square). Displayed as a small circular avatar next to testimonial quotes. The image is cropped to a circle — keep the face centered with adequate headroom. Minimum size: 200×200px. Plain or soft-blur backgrounds work best.', null=True, upload_to='testimonials/'),
        ),
    ]
