# Generated by Django 6.0.5 on 2026-06-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0036_alter_author_image_alter_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(help_text='Used in homepage hero slider (full width responsive banner). Keep main subject centered as image will be cropped on smaller screens. Ensure high quality wide composition.', upload_to='hero/slides/'),
        ),
        migrations.AlterField(
            model_name='servicecontentsection',
            name='image',
            field=models.ImageField(blank=True, help_text='Displayed alongside service content blocks. Used in responsive stacked layout on mobile. Keep subject centered for best visibility.', null=True, upload_to='services/content/'),
        ),
        migrations.AlterField(
            model_name='servicegalleryimage',
            name='after_image',
            field=models.ImageField(blank=True, help_text='Used in comparison slider for transformation display. Both images must have identical framing, angle, and lighting for accurate comparison.', null=True, upload_to='services/gallery/before_after/'),
        ),
        migrations.AlterField(
            model_name='servicegalleryimage',
            name='before_image',
            field=models.ImageField(blank=True, help_text='Used in comparison slider for transformation display. Both images must have identical framing, angle, and lighting for accurate comparison.', null=True, upload_to='services/gallery/before_after/'),
        ),
        migrations.AlterField(
            model_name='servicegalleryimage',
            name='image',
            field=models.ImageField(help_text='Used in service detail gallery grid. Maintain consistent composition and framing. Image adapts to responsive grid layout.', upload_to='services/gallery/'),
        ),
        migrations.AlterField(
            model_name='serviceheroimage',
            name='image',
            field=models.ImageField(help_text='Displayed at top of service pages as section banner. Responsive full-width image. Keep focal point centered for mobile cropping.', upload_to='services/hero/'),
        ),
    ]
