# Generated by Django 6.0.5 on 2026-06-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0037_alter_heroslide_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended: 400x400px (1:1 square). Used on blog posts and author profile pages. Keep face centered with good lighting.', null=True, upload_to='authors/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='Recommended: 1920x1080px (16:9). Used as full-width top banner on the homepage. Keep subject centered for responsive cropping.', upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='blogcontentsection',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200x800px (3:2). Used as inline image within blog article content. Full-width on mobile — keep subject centered.', null=True, upload_to='blog/sections/'),
        ),
        migrations.AlterField(
            model_name='blogdocumentblock',
            name='file',
            field=models.FileField(help_text='Downloadable document for blog posts. Accepted: PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX. Max file size: 20MB.', upload_to='blog/documents/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200x675px (16:9). Used as thumbnail in blog listing cards and previews. Cards use fixed aspect ratio — keep subject centered.', null=True, upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1920x1080px (16:9). Used as full-width hero at top of blog article pages. Keep subject centered for responsive cropping.', null=True, upload_to='blog/hero/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200x630px (1.91:1). Used for Facebook, LinkedIn, and Slack previews. Text and branding should stay within center 80%.', null=True, upload_to='blog/og/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='twitter_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200x600px (2:1). Used for X/Twitter large summary cards. Text and key visuals should stay in center safe area.', null=True, upload_to='blog/twitter/'),
        ),
        migrations.AlterField(
            model_name='brandlogo',
            name='logo',
            field=models.ImageField(help_text='Recommended: SVG or transparent PNG (min 300px width). Used in Trust Bar / brands carousel section. SVG ensures crisp rendering at all sizes.', upload_to='brands/'),
        ),
        migrations.AlterField(
            model_name='freetrialattachment',
            name='file',
            field=models.FileField(help_text='File attachment for free trial requests. Accepted: JPG, PNG, PDF, DOC, DOCX, ZIP. Max file size: 20MB.', upload_to='free_trial_attachments/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1920x1080px (16:9). Used as full-width background for the homepage hero section. Keep subject centered for responsive cropping.', null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(help_text='Recommended: 1920x1080px (16:9). Used in homepage hero slider (full width responsive banner). Keep subject centered for responsive cropping.', upload_to='hero/slides/'),
        ),
        migrations.AlterField(
            model_name='pricingconfigcard',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended: 600x400px (3:2). Used in the pricing configurator card grid. Cards use fixed aspect ratio — keep subject centered.', null=True, upload_to='pricing_config/'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended: 600x400px (3:2). Used inside pricing plan cards. Cards use fixed aspect ratio — keep subject centered.', null=True, upload_to='pricing/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='hero_background',
            field=models.ImageField(blank=True, help_text='Recommended: 1920x1080px (16:9). Used as full-width hero background on service pages. Keep subject centered for responsive cropping.', null=True, upload_to='services/hero/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended: 800x600px (4:3). Used in service cards, mega menu, and homepage sections. Cards use fixed aspect ratio — keep focal point centered.', null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='servicecontentsection',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended: 800x800px (1:1 square). Used beside text content in service sections. Stacks vertically on mobile — keep subject centered.', null=True, upload_to='services/content/'),
        ),
        migrations.AlterField(
            model_name='servicegalleryimage',
            name='after_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200x800px (3:2). Used in comparison slider for transformation display. Both images must have identical framing, angle, and lighting.', null=True, upload_to='services/gallery/before_after/'),
        ),
        migrations.AlterField(
            model_name='servicegalleryimage',
            name='before_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200x800px (3:2). Used in comparison slider for transformation display. Both images must have identical framing, angle, and lighting.', null=True, upload_to='services/gallery/before_after/'),
        ),
        migrations.AlterField(
            model_name='servicegalleryimage',
            name='image',
            field=models.ImageField(help_text='Recommended: 1200x800px (3:2). Used in service detail gallery grid. Maintain consistent composition and framing across all images.', upload_to='services/gallery/'),
        ),
        migrations.AlterField(
            model_name='serviceheroimage',
            name='image',
            field=models.ImageField(help_text='Recommended: 1600x900px (16:9). Used as section banner at top of service pages. Keep focal point centered for mobile cropping.', upload_to='services/hero/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, help_text='Recommended: 400x400px (1:1 square). Used in team member cards on about/team page. Frame face in center with shoulders visible.', null=True, upload_to='team/'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=models.ImageField(blank=True, help_text='Recommended: SVG or transparent PNG (min 200px width). Used in technology / expertise partner grid. SVG strongly preferred for crisp rendering.', null=True, upload_to='technology/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Recommended: 200x200px (1:1 square). Used as circular avatar next to testimonial quotes. Keep face centered with adequate headroom.', null=True, upload_to='testimonials/'),
        ),
    ]
