# Generated by Django 6.0.5 on 2026-06-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0038_alter_author_image_alter_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingconfigcard',
            name='banner_bg_color',
            field=models.CharField(default='#FF8A50', help_text='Banner background color (HEX)', max_length=20),
        ),
        migrations.AddField(
            model_name='pricingconfigcard',
            name='banner_expiry',
            field=models.DateTimeField(blank=True, help_text='Auto-hide banner after this date', null=True),
        ),
        migrations.AddField(
            model_name='pricingconfigcard',
            name='banner_icon',
            field=models.CharField(blank=True, choices=[('', 'None'), ('fire', 'Fire'), ('star', 'Star'), ('crown', 'Crown'), ('bolt', 'Lightning'), ('card_giftcard', 'Gift'), ('local_offer', 'Tag')], default='', help_text='Optional icon displayed before banner text', max_length=50),
        ),
        migrations.AddField(
            model_name='pricingconfigcard',
            name='banner_priority',
            field=models.PositiveIntegerField(default=0, help_text='Higher priority displays first'),
        ),
        migrations.AddField(
            model_name='pricingconfigcard',
            name='banner_text',
            field=models.CharField(blank=True, help_text='e.g. "Limited Time Offer", "Save 30%"', max_length=100),
        ),
        migrations.AddField(
            model_name='pricingconfigcard',
            name='banner_text_color',
            field=models.CharField(default='#FFFFFF', help_text='Banner text color (HEX)', max_length=20),
        ),
        migrations.AddField(
            model_name='pricingconfigcard',
            name='banner_type',
            field=models.CharField(choices=[('discount', 'Discount'), ('popular', 'Popular'), ('recommended', 'Recommended'), ('new', 'New'), ('custom', 'Custom')], default='custom', help_text='Visual style for the banner', max_length=20),
        ),
        migrations.AddField(
            model_name='pricingconfigcard',
            name='show_banner',
            field=models.BooleanField(default=False, help_text='Show promotion banner above card'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='banner_bg_color',
            field=models.CharField(default='#FF8A50', help_text='Banner background color (HEX)', max_length=20),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='banner_expiry',
            field=models.DateTimeField(blank=True, help_text='Auto-hide banner after this date', null=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='banner_icon',
            field=models.CharField(blank=True, choices=[('', 'None'), ('fire', 'Fire'), ('star', 'Star'), ('crown', 'Crown'), ('bolt', 'Lightning'), ('card_giftcard', 'Gift'), ('local_offer', 'Tag')], default='', help_text='Optional icon displayed before banner text', max_length=50),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='banner_priority',
            field=models.PositiveIntegerField(default=0, help_text='Higher priority displays first'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='banner_text',
            field=models.CharField(blank=True, help_text='e.g. "Limited Time Offer", "Save 30%"', max_length=100),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='banner_text_color',
            field=models.CharField(default='#FFFFFF', help_text='Banner text color (HEX)', max_length=20),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='banner_type',
            field=models.CharField(choices=[('discount', 'Discount'), ('popular', 'Popular'), ('recommended', 'Recommended'), ('new', 'New'), ('custom', 'Custom')], default='custom', help_text='Visual style for the banner', max_length=20),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='show_banner',
            field=models.BooleanField(default=False, help_text='Show promotion banner above card'),
        ),
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended Size: 200 × 200 px\nAspect Ratio: 1:1 (square, border-radius: 50%)\nDisplay Usage: Blog post author avatar\nComponents: blog/[slug]/page.tsx\nRendering: object-fit: cover, border-radius: 50%\nHero avatar: 40 × 40 px\nAuthor card: 52 × 52 px\nSafe Area: Center face — small display size means tight crop\n  — Ensure face is centered and well-lit, with minimal background', null=True, upload_to='authors/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='Recommended Size: 1920 × 1080 px\nAspect Ratio: 16:9\nDisplay Usage: Full-width top banner on homepage\nRendering: object-fit: cover\nSafe Area: Keep text/CTA within center 60%\n  — Image is cropped at all breakpoints', upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='blogcontentsection',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended Size: 1200 × 900 px\nAspect Ratio: 4:3 (various; intrinsic height or fixed 240px in gallery)\nDisplay Usage: Inline images within blog article content (BlockRenderer.tsx)\nRendering Modes:\n  — Standard: max-width: 100%, intrinsic height maintained\n  — Gallery: width: 100%, height: 240px fixed, object-fit: cover\n  — Full-width: width: 100%, height: auto\nGallery grid: 2-col desktop → 1-col (<=640px)\nSafe Area: Center 70%\n  — Gallery items are cropped to 240px height; others show full image', null=True, upload_to='blog/sections/'),
        ),
        migrations.AlterField(
            model_name='blogdocumentblock',
            name='file',
            field=models.FileField(help_text='Type: Downloadable document for blog posts\nAccepted Formats: PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX\nMax File Size: 20 MB\nDisplayed as download link, NOT rendered inline', upload_to='blog/documents/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Recommended Size: 1600 × 900 px\nAspect Ratio: 16:9 (featured cards), 16:10 (regular cards)\nDisplay Usage: Blog listing card thumbnails (BlogClient.tsx)\nRendering: object-fit: cover, overflow: hidden\nFeatured card: aspect-ratio: 16/9, hover scale(1.04)\nRegular card: aspect-ratio: 16/10, hover scale(1.05)\nRelated post card: aspect-ratio: 16/9, hover scale(1.04)\nGrid: auto-fill minmax(340px, 1fr), single column (<=768px)\nSafe Area: Center 70%\n  — Works across 3 different card layouts with slight ratio variations', null=True, upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Recommended Size: 1920 × 1080 px\nAspect Ratio: 16:9 (max-height: 480px with width: 100%)\nDisplay Usage: Blog detail hero / featured image\nRendering: object-fit: cover, max-height: 480px, border-radius: 14px\nSafe Area: Keep focal point within center 70%\n  — Full-width image cropped to max 480px height', null=True, upload_to='blog/hero/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Recommended Size: 1200 × 630 px\nAspect Ratio: 1.91:1\nDisplay Usage: Facebook / LinkedIn / Slack / Discord link previews\nSafe Area: Keep text and branding within center 80%\n  — Twitter/X previews may crop top/bottom\n  — Minimum: 600 × 315 px; Maximum: 1200 × 630 px', null=True, upload_to='blog/og/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='twitter_image',
            field=models.ImageField(blank=True, help_text='Recommended Size: 1200 × 600 px\nAspect Ratio: 2:1\nDisplay Usage: X/Twitter large summary card\nSafe Area: Keep key visuals in center safe area\n  — Large card format; avoid text in bottom 20%\n  — Twitter may add overlay text at bottom', null=True, upload_to='blog/twitter/'),
        ),
        migrations.AlterField(
            model_name='brandlogo',
            name='logo',
            field=models.ImageField(help_text='Recommended Size: SVG preferred, PNG min 260 × 64 px\nAspect Ratio: Landscape / horizontal (constrained to 130 × 32 px max)\nDisplay Usage: Trust bar / brand logo carousel (BrandLogos.tsx)\nRendering: Cell 160 × 48 px, SVG max 130 × 32 px\nFORMAT: SVG strongly preferred for crisp rendering\n  — If PNG, ensure logo is legible at 32px height', upload_to='brands/'),
        ),
        migrations.AlterField(
            model_name='freetrialattachment',
            name='file',
            field=models.FileField(help_text='Type: File attachment for free trial requests\nAccepted Formats: JPG, PNG, PDF, DOC, DOCX, ZIP\nMax File Size: 20 MB\nThis is an admin-facing upload — no frontend rendering', upload_to='free_trial_attachments/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Recommended Size: 1920 × 1080 px\nAspect Ratio: 16:9 (background-size: cover)\nDisplay Usage: Homepage Hero decorative background\nRendering: ::before pseudo-element, background-size: cover\nOpacity: 0.15 (decorative only, dark overlay on top)\nSafe Area: Decorative only — image is heavily overlaid\n  — Any subject will be barely visible through dark overlay', null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(help_text='Recommended Size: 1600 × 1200 px\nAspect Ratio: 4:3 (rendered as aspect-ratio: 4/3)\nDisplay Usage: Homepage Hero Slider (Hero.tsx)\nRendering: object-fit: cover, overflow: hidden\nDesktop: 2-column grid layout\nTablet (<=992px): Single column, max-width 520px\nMobile (<=576px): Full width with reduced padding\nSafe Area: Keep important content within center 70%\n  — Image is cropped on all viewports via overflow:hidden', upload_to='hero/slides/'),
        ),
        migrations.AlterField(
            model_name='pricingconfigcard',
            name='image',
            field=models.ImageField(blank=True, help_text="Recommended Size: 800 × 600 px\nAspect Ratio: 4:3 (no fixed CSS ratio; fixed container height)\nDisplay Usage: Pricing configurator card image (PricingConfigurator.tsx)\nRendering: object-fit: contain (NOT cover — full image visible)\nContainer height: 280px desktop → 200px (<=640px)\nHover: scale(1.05)\nSafe Area: Entire image visible (object-fit: contain)\n  — Background/edges will be visible if image doesn't fill container", null=True, upload_to='pricing_config/'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended Size: 600 × 400 px\nAspect Ratio: 3:2 (no fixed CSS ratio; fixed container height)\nDisplay Usage: Pricing plan card image (PricingClient.tsx)\nRendering: object-fit: cover, overflow: hidden\nContainer height: 160px desktop → 130px (<=768px) → 110px (<=480px)\nSafe Area: Center 70%\n  — Fixed-height container crops images of varying proportions', null=True, upload_to='pricing/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='hero_background',
            field=models.ImageField(blank=True, help_text='Recommended Size: 1600 × 1200 px\nAspect Ratio: 4:3 (heroRight container has aspect-ratio: 4/3)\nDisplay Usage: Service detail page hero background\nRendering: object-fit: cover, overflow: hidden (HeroCarousel.tsx)\nDesktop: Split layout (text left, image right)\nMobile (<=968px): Single column, image stacks below text\nSafe Area: Keep focal point within center 70%\n  — Image fills its container at all sizes', null=True, upload_to='services/hero/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended Size: 800 × 600 px\nAspect Ratio: ~4:3 (no CSS aspect-ratio set; height: 192px / 12rem)\nDisplay Usage: Service cards in homepage + services listing + mega menu\nComponents: ServiceCard.tsx (h-48), StackedServices.tsx, homepage.module.css\nRendering: object-fit: cover, overflow: hidden\nCard Grid: 1-col mobile → 2-col (>=640px) → 3-col (>=1024px) → 4-col (>=1280px)\nStacked Service: height clamp(280px, 40vh, 380px), 45-55% card width\nHomepage section: fixed height 240px\nSafe Area: Keep subject within center 70%\n  — Image is cropped via object-fit:cover on all devices', null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='servicecontentsection',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended Size: 1200 × 800 px\nAspect Ratio: 3:2 (no fixed CSS ratio; height: 400px)\nDisplay Usage: Service detail content sections (services/[slug]/page.tsx)\nRendering: width: 100%, height: 400px, object-fit: cover\nDesktop: 2-column grid (text + image)\nMobile (<=900px): Single column, image stacks below text\nHover: scale(1.03) transform on image\nSafe Area: Center 70% — subject will be cropped at height boundary\n  — Ensures uniform section height regardless of image proportions', null=True, upload_to='services/content/'),
        ),
        migrations.AlterField(
            model_name='servicegalleryimage',
            name='after_image',
            field=models.ImageField(blank=True, help_text='Recommended Size: 1600 × 1200 px\nAspect Ratio: 4:3 (aspect-ratio: 4/3)\nDisplay Usage: Service gallery — BEFORE/AFTER comparison pair\nComponent: BeforeAfterSlider.tsx\nRendering: Two <img> elements, object-fit: cover, clip-path overlay\nInteractive: Slider handle for user to drag and compare\nSame grid behavior: 3/2/1 columns\nCRITICAL: Both images MUST have identical framing / angle / lighting\nSafe Area: Center 70% — slider clips the before image\n  — Any misalignment between images will be obvious to users', null=True, upload_to='services/gallery/before_after/'),
        ),
        migrations.AlterField(
            model_name='servicegalleryimage',
            name='before_image',
            field=models.ImageField(blank=True, help_text='Recommended Size: 1600 × 1200 px\nAspect Ratio: 4:3 (aspect-ratio: 4/3)\nDisplay Usage: Service gallery — BEFORE/AFTER comparison pair\nComponent: BeforeAfterSlider.tsx\nRendering: Two <img> elements, object-fit: cover, clip-path overlay\nInteractive: Slider handle for user to drag and compare\nSame grid behavior: 3/2/1 columns\nCRITICAL: Both images MUST have identical framing / angle / lighting\nSafe Area: Center 70% — slider clips the before image\n  — Any misalignment between images will be obvious to users', null=True, upload_to='services/gallery/before_after/'),
        ),
        migrations.AlterField(
            model_name='servicegalleryimage',
            name='image',
            field=models.ImageField(help_text='Recommended Size: 1600 × 1200 px\nAspect Ratio: 4:3 (aspect-ratio: 4/3 on slider container)\nDisplay Usage: Service gallery — single images\nComponents: BeforeAfterSlider.tsx, ServiceGalleryImage model\nRendering: object-fit: cover, overflow: hidden, clip-path on before image\nGrid: 3-col desktop → 2-col (<=1024px) → 1-col (<=640px)\nSafe Area: Center 70%\n  — Interactive comparison slider; user drags to reveal before/after', upload_to='services/gallery/'),
        ),
        migrations.AlterField(
            model_name='serviceheroimage',
            name='image',
            field=models.ImageField(help_text='Recommended Size: 1600 × 1200 px\nAspect Ratio: 4:3\nDisplay Usage: Service hero carousel slides (HeroCarousel.tsx)\nRendering: object-fit: cover, overflow: hidden\nSame layout as hero background above\nSafe Area: Center 70%\n  — Images are full-width, cropped on all devices', upload_to='services/hero/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, help_text='Recommended Size: 400 × 400 px\nAspect Ratio: 1:1 (square)\nDisplay Usage: Team member profile photo\nRendering: Circular or rounded crop\nFrame face centered with shoulders visible\nSafe Area: Center 50% — outer edges may be cropped', null=True, upload_to='team/'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=models.ImageField(blank=True, help_text='Recommended Size: SVG preferred, PNG min 120 × 120 px\nAspect Ratio: 1:1 (square; displayed in circular container)\nDisplay Usage: Technology expertise grid (TechExpertiseSection.tsx)\nRendering: object-fit: contain in circular container\nCircle: 100px desktop → 80px (<=768px) → 64px (<=480px)\nLogo max: 60 × 60 px\nFORMAT: SVG strongly preferred\n  — Icons are small; crisp vector art looks much better', null=True, upload_to='technology/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Recommended Size: 200 × 200 px\nAspect Ratio: 1:1 (square, border-radius: 50%)\nDisplay Usage: Testimonial circular avatar (TestimonialCarousel.tsx)\nRendering: object-fit: cover, border-radius: 50%, overflow: hidden\nDesktop: 90 × 90 px circle\nMobile (<=600px): 70 × 70 px circle\nSafe Area: Center face with adequate headroom\n  — Image is aggressively cropped to a small circle', null=True, upload_to='testimonials/'),
        ),
    ]
