# Generated by Django 6.0.5 on 2026-06-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0039_pricingconfigcard_banner_bg_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPromotionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text='Show this promotion on the pricing page')),
                ('badge_text', models.CharField(blank=True, help_text='e.g. "Limited Time Offer", "Special Deal"', max_length=100)),
                ('title', models.CharField(blank=True, help_text='e.g. "Get 30% Off This Month"', max_length=255)),
                ('subtitle', models.CharField(blank=True, help_text='Short supporting text', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Rich text description of the promotion')),
                ('image_desktop', models.ImageField(blank=True, help_text='Desktop banner (recommended: 1920×600)', null=True, upload_to='promotions/')),
                ('image_mobile', models.ImageField(blank=True, help_text='Mobile banner (recommended: 1080×1080)', null=True, upload_to='promotions/')),
                ('cta_text', models.CharField(blank=True, help_text='e.g. "Claim Offer", "Get Started"', max_length=100)),
                ('cta_url', models.CharField(blank=True, default='/pricing', help_text='Button link', max_length=500)),
                ('bg_color', models.CharField(default='#0F172A', help_text='Section background color (HEX)', max_length=20)),
                ('text_color', models.CharField(default='#FFFFFF', help_text='Main text color (HEX)', max_length=20)),
                ('accent_color', models.CharField(default='#FF8A50', help_text='Badge and CTA accent color (HEX)', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, help_text='Campaign start date', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Campaign end date (auto-hides after)', null=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order (if multiple promotions)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Promotion Section',
                'verbose_name_plural': 'Pricing Promotion Sections',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
