# Generated by Django 6.0.5 on 2026-06-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0040_pricingpromotionsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingpromotionsection',
            name='use_theme_color',
            field=models.BooleanField(default=True, help_text='Use theme CSS variables (--primary-color, --accent-color) instead of custom background color. Keeps the promotion visually consistent with the site design.'),
        ),
        migrations.AlterField(
            model_name='pricingpromotionsection',
            name='bg_color',
            field=models.CharField(default='#0F172A', help_text='Section background color (HEX). Only used if "Use Theme Color" is OFF.', max_length=20),
        ),
    ]
