# Generated by Django 6.0.5 on 2026-06-26 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_pricingpromotion_use_theme_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePricingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Basic", "Standard", "Premium"', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_pricing_cards/')),
                ('badge_text', models.CharField(blank=True, help_text='e.g. "Popular", "Best Value"', max_length=100)),
                ('badge_color', models.CharField(blank=True, help_text='HEX color for badge', max_length=20)),
                ('button_text', models.CharField(default='Select', max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_cards', to='cms.service')),
            ],
            options={
                'verbose_name': 'Service Pricing Card',
                'verbose_name_plural': 'Service Pricing Cards',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceUnitRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. "1-25 images", "26-100 images"', max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_ranges', to='cms.service')),
            ],
            options={
                'verbose_name': 'Service Unit Range',
                'verbose_name_plural': 'Service Unit Ranges',
                'ordering': ['sort_order'],
                'unique_together': {('service', 'label')},
            },
        ),
        migrations.CreateModel(
            name='ServicePricingCardPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Strikethrough original price', max_digits=10, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='cms.servicepricingcard')),
                ('unit_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_prices', to='cms.serviceunitrange')),
            ],
            options={
                'verbose_name': 'Service Pricing Card Price',
                'verbose_name_plural': 'Service Pricing Card Prices',
                'unique_together': {('card', 'unit_range')},
            },
        ),
    ]
