# Generated by Django 6.0.5 on 2026-06-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0042_servicepricingcard_serviceunitrange_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_alt',
            field=models.CharField(blank=True, help_text='Alt text for the featured image', max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='hero_image_alt',
            field=models.CharField(blank=True, help_text='Alt text for the hero image', max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_image_alt',
            field=models.CharField(blank=True, help_text='Alt text for the OG image', max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='twitter_image_alt',
            field=models.CharField(blank=True, help_text='Alt text for the Twitter image', max_length=200),
        ),
        migrations.AddField(
            model_name='brandlogo',
            name='logo_alt',
            field=models.CharField(blank=True, help_text='Alt text for the brand logo', max_length=200),
        ),
        migrations.AddField(
            model_name='herosection',
            name='background_image_alt',
            field=models.CharField(blank=True, help_text='Alt text for the hero background image', max_length=200),
        ),
        migrations.AddField(
            model_name='pricingconfigcard',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Alt text for the pricing card image', max_length=200),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Alt text for the pricing plan image', max_length=200),
        ),
        migrations.AddField(
            model_name='pricingpromotionsection',
            name='image_desktop_alt',
            field=models.CharField(blank=True, help_text='Alt text for the desktop promotion image', max_length=200),
        ),
        migrations.AddField(
            model_name='pricingpromotionsection',
            name='image_mobile_alt',
            field=models.CharField(blank=True, help_text='Alt text for the mobile promotion image', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_image_alt',
            field=models.CharField(blank=True, help_text='Alt text for the hero background image', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Alt text for the service thumbnail image', max_length=200),
        ),
        migrations.AddField(
            model_name='servicegalleryimage',
            name='after_image_alt',
            field=models.CharField(blank=True, help_text='Alt text for the after image', max_length=200),
        ),
        migrations.AddField(
            model_name='servicegalleryimage',
            name='before_image_alt',
            field=models.CharField(blank=True, help_text='Alt text for the before image', max_length=200),
        ),
        migrations.AddField(
            model_name='servicepricingcard',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Alt text for the pricing card image', max_length=200),
        ),
        migrations.AddField(
            model_name='teammember',
            name='photo_alt',
            field=models.CharField(blank=True, help_text='Alt text for the team member photo', max_length=200),
        ),
        migrations.AddField(
            model_name='technology',
            name='icon_alt',
            field=models.CharField(blank=True, help_text='Alt text for the technology icon', max_length=200),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='avatar_alt',
            field=models.CharField(blank=True, help_text='Alt text for the testimonial avatar', max_length=200),
        ),
    ]
