# Generated by Django 5.2.15 on 2026-07-10 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0043_banner_alt_text_blogpost_featured_image_alt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Why Choose Us', max_length=200)),
                ('highlighted_word', models.CharField(default='Choose', max_length=50)),
                ('subtitle', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Why Choose Us Section',
                'verbose_name_plural': 'Why Choose Us Section',
            },
        ),
        migrations.CreateModel(
            name='WhyChooseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('speed', models.BooleanField(default=False)),
                ('flexibility', models.BooleanField(default=False)),
                ('quality', models.BooleanField(default=False)),
                ('scalability', models.BooleanField(default=False)),
                ('cost_effectiveness', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.whychoosesection')),
            ],
            options={
                'verbose_name': 'Why Choose Item',
                'verbose_name_plural': 'Why Choose Items',
                'ordering': ['display_order'],
            },
        ),
    ]
