# Generated by Django 5.2.15 on 2026-07-13 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0044_whychoosesection_whychooseitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseFeatureSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Why Choose Us', max_length=200)),
                ('subtitle', models.TextField(blank=True, default='')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='why-choose-features/')),
                ('featured_image_alt', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Why Choose Feature Section',
                'verbose_name_plural': 'Why Choose Feature Section',
            },
        ),
        migrations.CreateModel(
            name='WhyChooseFeatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='why-choose-features/icons/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.whychoosefeaturesection')),
            ],
            options={
                'verbose_name': 'Why Choose Feature Item',
                'verbose_name_plural': 'Why Choose Feature Items',
                'ordering': ['display_order'],
            },
        ),
    ]
