# Generated by Django 5.2.15 on 2026-07-14 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0046_faq_service_is_contact_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='brand_section_title',
            field=models.CharField(blank=True, default='Trusted by Brands & Partners', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='pricing_cta_link',
            field=models.CharField(blank=True, default='/free-trial', max_length=500),
        ),
        migrations.AddField(
            model_name='service',
            name='pricing_cta_text',
            field=models.CharField(blank=True, default='Get Started', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='pricing_starting_price',
            field=models.CharField(blank=True, default='', help_text='e.g. "$5.00/image"', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='pricing_title',
            field=models.CharField(blank=True, default='Pricing', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='process_section_title',
            field=models.CharField(blank=True, default='Process & Workflow', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='tools_section_title',
            field=models.CharField(blank=True, default='Tools We Use', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='why_choose_title',
            field=models.CharField(blank=True, default='Why Choose Us', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='why_need_section_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='service',
            name='why_need_section_title',
            field=models.CharField(blank=True, default='Why Should You Need Our Service', max_length=200),
        ),
        migrations.CreateModel(
            name='ServiceBrandLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(help_text='Brand logo image', upload_to='service_brands/')),
                ('logo_alt', models.CharField(blank=True, help_text='Alt text for brand logo', max_length=200)),
                ('brand_name', models.CharField(help_text='Brand name', max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_logos', to='cms.service')),
            ],
            options={
                'verbose_name': 'Service Brand Logo',
                'verbose_name_plural': 'Service Brand Logos',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceClientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(help_text='Client name', max_length=200)),
                ('company', models.CharField(blank=True, help_text='Company name', max_length=200)),
                ('designation', models.CharField(blank=True, help_text='Job title / designation', max_length=200)),
                ('photo', models.ImageField(blank=True, help_text='Client photo', null=True, upload_to='service_feedbacks/')),
                ('photo_alt', models.CharField(blank=True, help_text='Alt text for client photo', max_length=200)),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Rating 1-5')),
                ('review', models.TextField(blank=True, help_text='Client review text')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_feedbacks', to='cms.service')),
            ],
            options={
                'verbose_name': 'Service Client Feedback',
                'verbose_name_plural': 'Service Client Feedbacks',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceEEAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.TextField(blank=True, help_text='Experience description')),
                ('expertise', models.TextField(blank=True, help_text='Expertise description')),
                ('authoritativeness', models.TextField(blank=True, help_text='Authoritativeness description')),
                ('trustworthiness', models.TextField(blank=True, help_text='Trustworthiness description')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eeat', to='cms.service')),
            ],
            options={
                'verbose_name': 'Service EEAT',
                'verbose_name_plural': 'Service EEAT',
            },
        ),
        migrations.CreateModel(
            name='ServicePricingTierCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Card name e.g. "Basic", "Standard"', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Card description')),
                ('price', models.CharField(blank=True, help_text='e.g. "$5.00"', max_length=100)),
                ('original_price', models.CharField(blank=True, help_text='Strikethrough price e.g. "$8.00"', max_length=100)),
                ('features', models.JSONField(blank=True, default=list, help_text='List of features as JSON array')),
                ('is_popular', models.BooleanField(default=False, help_text='Highlight as popular')),
                ('badge_text', models.CharField(blank=True, help_text='e.g. "Popular", "Best Value"', max_length=100)),
                ('badge_color', models.CharField(blank=True, help_text='HEX color for badge', max_length=20)),
                ('button_text', models.CharField(default='Select', max_length=100)),
                ('button_link', models.CharField(blank=True, default='/free-trial', max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tier_cards', to='cms.service')),
            ],
            options={
                'verbose_name': 'Service Pricing Tier Card',
                'verbose_name_plural': 'Service Pricing Tier Cards',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(default=1, help_text='Step number')),
                ('title', models.CharField(help_text='Step title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Step description')),
                ('image', models.ImageField(blank=True, help_text='Optional step image/icon', null=True, upload_to='service_process/')),
                ('image_alt', models.CharField(blank=True, help_text='Alt text for step image', max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='cms.service')),
            ],
            options={
                'verbose_name': 'Service Process Step',
                'verbose_name_plural': 'Service Process Steps',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Tool logo', null=True, upload_to='service_tools/')),
                ('logo_alt', models.CharField(blank=True, help_text='Alt text for tool logo', max_length=200)),
                ('name', models.CharField(help_text='Tool name', max_length=200)),
                ('short_description', models.TextField(blank=True, help_text='Short description')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='cms.service')),
            ],
            options={
                'verbose_name': 'Service Tool',
                'verbose_name_plural': 'Service Tools',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceWhyChooseCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_image', models.ImageField(blank=True, help_text='Optional icon/image', null=True, upload_to='service_why_choose/')),
                ('title', models.CharField(help_text='Card title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Card description')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_choose_cards', to='cms.service')),
            ],
            options={
                'verbose_name': 'Why Choose Card',
                'verbose_name_plural': 'Why Choose Cards',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceWhyNeedFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Feature title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Feature description')),
                ('icon_image', models.ImageField(blank=True, help_text='Optional icon/image', null=True, upload_to='service_why_need/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_need_features', to='cms.service')),
            ],
            options={
                'verbose_name': 'Why Need Feature',
                'verbose_name_plural': 'Why Need Features',
                'ordering': ['display_order'],
            },
        ),
    ]
