# Generated by Django 5.2.15 on 2026-07-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0047_service_brand_section_title_service_pricing_cta_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='pricing_badge_text',
            field=models.CharField(blank=True, default='', help_text='e.g. "Simple, Transparent Pricing"', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='pricing_cta2_link',
            field=models.CharField(blank=True, default='/pricing', max_length=500),
        ),
        migrations.AddField(
            model_name='service',
            name='pricing_cta2_text',
            field=models.CharField(blank=True, default='View All Plans', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='pricing_description',
            field=models.TextField(blank=True, default='', help_text='Description text for pricing section'),
        ),
        migrations.AddField(
            model_name='service',
            name='pricing_features',
            field=models.JSONField(blank=True, default=list, help_text='List of features as JSON array'),
        ),
        migrations.AddField(
            model_name='service',
            name='pricing_heading',
            field=models.CharField(blank=True, default='', help_text='Main heading for premium pricing section', max_length=300),
        ),
        migrations.AddField(
            model_name='service',
            name='pricing_notes',
            field=models.CharField(blank=True, default='', help_text='Short notes about pricing', max_length=500),
        ),
        migrations.AddField(
            model_name='service',
            name='pricing_unit',
            field=models.CharField(blank=True, default='/image', help_text='Price unit e.g. "/image", "/hour", "/project"', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='pricing_starting_price',
            field=models.CharField(blank=True, default='', help_text='e.g. "$5.00"', max_length=100),
        ),
    ]
