# Generated by Django 5.2.15 on 2026-07-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0048_service_pricing_premium_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebrandlogo',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show on website'),
        ),
        migrations.AddField(
            model_name='servicecontentsection',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show on website'),
        ),
        migrations.AddField(
            model_name='serviceeeat',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show EEAT section on service page'),
        ),
        migrations.AddField(
            model_name='serviceheroimage',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show on website'),
        ),
    ]
