# Generated by Django 5.2.15 on 2026-07-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0049_servicebrandlogo_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandlogo',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show on website'),
        ),
    ]
