# Generated by Django 5.2.15 on 2026-07-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0050_brandlogo_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepricingtiercard',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='List of features as JSON array', null=True),
        ),
    ]
