# Generated by Django 5.2.15 on 2026-07-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0051_alter_servicepricingtiercard_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Show in featured section'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Show on website'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Featured service (highlighted on homepage)'),
        ),
    ]
