# Generated by Django 5.2.15 on 2026-07-19 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0052_add_db_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freetrial',
            options={'ordering': ('-created_at',), 'verbose_name': 'Trial Request', 'verbose_name_plural': 'Trial Requests'},
        ),
        migrations.AlterModelOptions(
            name='herosection',
            options={'verbose_name': 'Hero Section', 'verbose_name_plural': 'Hero Sections'},
        ),
        migrations.AlterModelOptions(
            name='pricingconfigcardprice',
            options={'ordering': ('unit_range__order',), 'verbose_name': 'Pricing Card Price', 'verbose_name_plural': 'Pricing Card Prices'},
        ),
        migrations.AlterModelOptions(
            name='pricingconfigsection',
            options={'verbose_name': 'Pricing Configurator', 'verbose_name_plural': 'Pricing Configurators'},
        ),
        migrations.AlterModelOptions(
            name='pricingpromotionsection',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'Promotion Campaign', 'verbose_name_plural': 'Promotion Campaigns'},
        ),
        migrations.AlterModelOptions(
            name='whychoosefeaturesection',
            options={'verbose_name': 'Why Choose Feature Section', 'verbose_name_plural': 'Why Choose Feature Sections'},
        ),
        migrations.AlterModelOptions(
            name='whychoosesection',
            options={'verbose_name': 'Why Choose Section', 'verbose_name_plural': 'Why Choose Sections'},
        ),
    ]
