# Generated by Django 5.2.15 on 2026-09-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0053_alter_freetrial_options_alter_herosection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='title_color',
            field=models.CharField(blank=True, default='', help_text='Custom hex color for the hero title (e.g. #FF8A50). Default is black.', max_length=50),
        ),
        migrations.AddField(
            model_name='page',
            name='title_color',
            field=models.CharField(blank=True, default='', help_text='Custom hex color for the page title (e.g. #FF8A50). Default is black.', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='title_color',
            field=models.CharField(blank=True, default='', help_text='Custom hex color for the service title (e.g. #FF8A50). Default is black.', max_length=50),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content_blocks',
            field=models.JSONField(blank=True, default=list, help_text='Modular content blocks array. Supported types: heading, text, image, image_with_text, gallery, code, callout, faq, list, table, step, divider, stats, quote, cta, full_width_image', null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='faq_schema',
            field=models.JSONField(blank=True, default=list, help_text='FAQPage structured data items: [{"question":"...","answer":"..."}]', null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='key_takeaways',
            field=models.JSONField(blank=True, default=list, help_text='Key takeaways / learning objectives as JSON array of strings', null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='secondary_keywords',
            field=models.JSONField(blank=True, default=list, help_text='Secondary keywords as JSON array', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='content_blocks',
            field=models.JSONField(blank=True, default=list, help_text='Modular content blocks array. Supported types: heading, text, image, image_with_text, gallery, code, callout, faq, list, table, step, divider', null=True),
        ),
    ]
