# Generated by Django 5.2.15 on 2026-09-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0054_herosection_title_color_page_title_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='hero_title',
            field=models.CharField(blank=True, default='', help_text='Primary H1 headline for the hero section. Overrides the service title in the hero. If blank, hero_subtitle is used.', max_length=255),
        ),
    ]
