# Generated by Django 5.2.15 on 2026-09-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0055_service_hero_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicegalleryimage',
            name='after_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/gallery/before_after/'),
        ),
        migrations.AlterField(
            model_name='servicegalleryimage',
            name='after_image_alt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='servicegalleryimage',
            name='before_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/gallery/before_after/'),
        ),
        migrations.AlterField(
            model_name='servicegalleryimage',
            name='before_image_alt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='servicegalleryimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/gallery/'),
        ),
        migrations.AlterField(
            model_name='serviceheroimage',
            name='image',
            field=models.ImageField(upload_to='services/hero/'),
        ),
    ]
