# Generated by Django 5.2.15 on 2026-09-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0056_alter_servicegalleryimage_after_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicegalleryimage',
            name='after_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1600 × 1200 px (4:3)', null=True, upload_to='services/gallery/before_after/'),
        ),
        migrations.AlterField(
            model_name='servicegalleryimage',
            name='before_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1600 × 1200 px (4:3)', null=True, upload_to='services/gallery/before_after/'),
        ),
        migrations.AlterField(
            model_name='servicegalleryimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended: 1600 × 1200 px (4:3)', null=True, upload_to='services/gallery/'),
        ),
        migrations.AlterField(
            model_name='serviceheroimage',
            name='image',
            field=models.ImageField(help_text='Recommended: 1600 × 1200 px (4:3)', upload_to='services/hero/'),
        ),
    ]
