# Generated by Django 5.2.15 on 2026-09-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0057_alter_servicegalleryimage_after_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='faq_title',
            field=models.CharField(blank=True, default='', help_text='Custom heading for FAQs section. Leave blank for "[Service Title] - FAQs"', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='overview_title',
            field=models.CharField(blank=True, default='', help_text='Custom heading for Overview section. Leave blank for "Overview of [Service Title]"', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='review_title',
            field=models.CharField(blank=True, default='', help_text='Custom heading for Reviews section. Leave blank for "Our Clients & Reviews"', max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='why_choose_title',
            field=models.CharField(blank=True, default='Why Choose Us', help_text='Heading for "Why Choose Us" section', max_length=200),
        ),
    ]
