# Generated by Django 5.2.15 on 2026-09-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0058_service_faq_title_service_overview_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='faq_title_color',
            field=models.CharField(blank=True, default='', help_text='Color for FAQs heading (HEX e.g. #000000 or #FF8A50)', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='overview_title_color',
            field=models.CharField(blank=True, default='', help_text='Color for Overview section heading (HEX e.g. #000000 or #FF8A50)', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='pricing_heading_color',
            field=models.CharField(blank=True, default='', help_text='Color for main Pricing section heading (HEX e.g. #000000 or #FF8A50)', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='process_title_color',
            field=models.CharField(blank=True, default='', help_text='Color for "Process & Workflow" heading (HEX e.g. #000000 or #FF8A50)', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='review_title_color',
            field=models.CharField(blank=True, default='', help_text='Color for Reviews heading (HEX e.g. #000000 or #FF8A50)', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='why_choose_title_color',
            field=models.CharField(blank=True, default='', help_text='Color for "Why Choose Us" heading (HEX e.g. #000000 or #FF8A50)', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='why_need_title_color',
            field=models.CharField(blank=True, default='', help_text='Color for "Why Should You Need Our Service" heading (HEX e.g. #000000 or #FF8A50)', max_length=50),
        ),
    ]
