# Generated by Django 5.2.15 on 2026-09-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0059_service_faq_title_color_service_overview_title_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageCTASection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Show this CTA section on the homepage')),
                ('badge_text', models.CharField(blank=True, default='Free Trial Available', help_text='Small badge/tag above the title (optional)', max_length=100)),
                ('title', models.CharField(default='Experience Our World-Class Photo Editing', help_text='Main CTA heading', max_length=255)),
                ('title_color', models.CharField(blank=True, default='', help_text='Custom hex color for heading (e.g. #0F172A or #FF8A50). Leave blank for default.', max_length=50)),
                ('subtitle', models.TextField(blank=True, default='Get your quote within 45 minutes. Upload your images via Wetransfer or Dropbox. Your first (3-5) images are free. No credit card required.', help_text='Supporting subtitle or description text')),
                ('primary_button_is_active', models.BooleanField(default=True, help_text='Enable / show Primary Button')),
                ('primary_button_text', models.CharField(default='Start Free Trial →', help_text='Text for primary button', max_length=100)),
                ('primary_button_link', models.CharField(default='/free-trial', help_text='Link URL for primary button', max_length=255)),
                ('secondary_button_is_active', models.BooleanField(default=True, help_text='Enable / show Secondary Button (Turn off if you want only 1 button)')),
                ('secondary_button_text', models.CharField(blank=True, default='Contact Us', help_text='Text for secondary button', max_length=100)),
                ('secondary_button_link', models.CharField(blank=True, default='/contact', help_text='Link URL for secondary button', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage CTA Section',
                'verbose_name_plural': 'Homepage CTA Section',
            },
        ),
    ]
