# Generated by Django 5.2.15 on 2026-09-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0060_homepagectasection'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='is_homepage_faq',
            field=models.BooleanField(default=True, help_text='Show this FAQ on the Homepage'),
        ),
        migrations.AddField(
            model_name='faq',
            name='is_portfolio_faq',
            field=models.BooleanField(default=False, help_text='Show this FAQ on the Portfolio page'),
        ),
    ]
