# Generated by Django 5.2.15 on 2026-09-11 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0061_faq_is_homepage_faq_faq_is_portfolio_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Page Category',
                'verbose_name_plural': 'Page Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='custom_schema',
            field=models.TextField(blank=True, default='', help_text='Custom JSON-LD schema (leave blank for automatic Article / BlogPosting schema)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='schema_type',
            field=models.CharField(choices=[('Article', 'Article (Standard)'), ('BlogPosting', 'BlogPosting'), ('TechArticle', 'TechArticle (Tutorial / Guide)'), ('NewsArticle', 'NewsArticle'), ('custom', 'Custom JSON-LD')], default='BlogPosting', help_text='Schema.org type for this blog post', max_length=50),
        ),
        migrations.AddField(
            model_name='freetrial',
            name='last_sms_sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when client was last notified', null=True),
        ),
        migrations.AddField(
            model_name='freetrial',
            name='sms_notes',
            field=models.TextField(blank=True, default='', help_text='Internal communication notes / SMS message content sent to client'),
        ),
        migrations.AddField(
            model_name='freetrial',
            name='sms_status',
            field=models.CharField(choices=[('pending', 'Pending (Not Sent)'), ('sent', 'SMS Sent'), ('contacted', 'Contacted via WhatsApp/Call'), ('not_required', 'Not Required')], default='pending', help_text='Client SMS/notification status', max_length=20),
        ),
        migrations.AddField(
            model_name='page',
            name='custom_schema',
            field=models.TextField(blank=True, default='', help_text='Custom JSON-LD structured data (paste valid JSON object, without <script> tags)'),
        ),
        migrations.AddField(
            model_name='page',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show page on the website'),
        ),
        migrations.AddField(
            model_name='page',
            name='schema_type',
            field=models.CharField(choices=[('none', 'None (No Schema)'), ('WebPage', 'WebPage (Standard Page)'), ('AboutPage', 'AboutPage'), ('ContactPage', 'ContactPage'), ('FAQPage', 'FAQPage'), ('Service', 'Service'), ('CollectionPage', 'CollectionPage'), ('custom', 'Custom JSON-LD')], default='WebPage', help_text='Schema.org structured data type for this page', max_length=50),
        ),
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Organize pages by category (e.g. Marketing, Legal, Company, Support)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='cms.pagecategory'),
        ),
    ]
