# Generated by Django 5.2.15 on 2026-09-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0062_pagecategory_blogpost_custom_schema_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freetrial',
            options={'ordering': ('-created_at',), 'verbose_name': 'Trial & Order Request', 'verbose_name_plural': 'Trial & Order Requests'},
        ),
        migrations.AddField(
            model_name='freetrial',
            name='country',
            field=models.CharField(blank=True, default='', help_text='Client country', max_length=100),
        ),
        migrations.AddField(
            model_name='freetrial',
            name='package_price',
            field=models.CharField(blank=True, default='', help_text='Package or plan price', max_length=100),
        ),
        migrations.AddField(
            model_name='freetrial',
            name='request_type',
            field=models.CharField(choices=[('free_trial', 'Free Trial Request'), ('order_request', 'Order Request')], default='free_trial', help_text='Whether this submission is a Free Trial or an Order Request', max_length=30),
        ),
        migrations.AlterField(
            model_name='freetrial',
            name='product_category',
            field=models.CharField(blank=True, choices=[('clothing', 'Clothing / Apparel'), ('electronics', 'Electronics'), ('jewelry', 'Jewelry / Watches'), ('home_garden', 'Home & Garden'), ('beauty', 'Beauty / Cosmetics'), ('food', 'Food & Beverage'), ('automotive', 'Automotive'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='freetrial',
            name='product_name',
            field=models.CharField(help_text='Product name or selected Service/Package title', max_length=300),
        ),
    ]
