# Generated by Django 5.2.15 on 2026-09-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0063_alter_freetrial_options_freetrial_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='available_locations',
            field=models.JSONField(blank=True, default=list, help_text='Locations where this service is available (e.g. Texas, California). Leave empty to make available in all locations.'),
        ),
    ]
