# Generated by Django 5.2.15 on 2026-09-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0064_service_available_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Value Title (e.g. "Quality First", "Speed", "Pixel-Perfect")', max_length=200)),
                ('description', models.TextField(help_text='Description of this value')),
                ('icon_name', models.CharField(blank=True, default='Star', help_text='Lucide icon name (e.g. Star, Zap, Sparkles, Shield, Globe, DollarSign, Award, CheckCircle, Heart, Users)', max_length=100)),
                ('icon_image', models.ImageField(blank=True, help_text='Optional custom icon or image file', null=True, upload_to='about/values/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Core Value',
                'verbose_name_plural': 'Our Core Values',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutMissionVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Card Title (e.g. "Our Mission", "Our Vision")', max_length=200)),
                ('description', models.TextField(help_text='Description text')),
                ('icon_name', models.CharField(blank=True, default='Target', help_text='Lucide icon name (e.g. Target, Eye, Compass, Flag, Shield, Award, Sparkles, Heart)', max_length=100)),
                ('icon_image', models.ImageField(blank=True, help_text='Optional custom icon or image file', null=True, upload_to='about/mission_vision/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mission & Vision',
                'verbose_name_plural': 'Mission & Vision',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutPageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_section_title', models.CharField(default='Mission & Vision', help_text='Title for Mission & Vision section', max_length=200)),
                ('mission_section_subtitle', models.TextField(blank=True, default='', help_text='Optional subtitle for Mission & Vision')),
                ('values_section_title', models.CharField(default='Our Core Values', help_text='Title for Core Values section', max_length=200)),
                ('values_section_subtitle', models.TextField(blank=True, default='', help_text='Optional subtitle for Core Values')),
                ('process_section_title', models.CharField(default='Our Simple 6-Step Process', help_text='Title for Process section', max_length=200)),
                ('process_section_subtitle', models.TextField(blank=True, default='', help_text='Optional subtitle for Process section')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page Setting',
                'verbose_name_plural': 'About Page Settings',
            },
        ),
        migrations.CreateModel(
            name='AboutProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.CharField(default='01', help_text='Step number badge (e.g. 01, 02, 03)', max_length=20)),
                ('title', models.CharField(help_text='Step title (e.g. "Request a Quote", "Get Your Quote")', max_length=200)),
                ('description', models.TextField(help_text='Description of this step')),
                ('icon_name', models.CharField(blank=True, default='FileText', help_text='Lucide icon name (e.g. FileText, Mail, ClipboardCheck, Image, CheckCircle, TrendingUp, Sparkles, Send)', max_length=100)),
                ('icon_image', models.ImageField(blank=True, help_text='Optional custom icon or image file', null=True, upload_to='about/process/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Process Step',
                'verbose_name_plural': 'Our Simple 6-Step Process',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
