# Generated by Django 5.2.15 on 2026-09-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0065_aboutcorevalue_aboutmissionvision_aboutpagesetting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutStorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='More Than a Photo Editing Company', help_text='Main heading (e.g. More Than a Photo Editing Company)', max_length=255)),
                ('subtitle', models.TextField(blank=True, default='We are a team of passionate photo editors, retouchers, and creative professionals dedicated to helping businesses present their products in the best possible light.', help_text='Subtitle or tagline below the main heading')),
                ('paragraph_1', models.TextField(blank=True, default='Founded with a vision to democratize professional photo editing, PicPicxels has grown from a small team of skilled retouchers into a global studio serving hundreds of clients across multiple industries.', help_text='First story paragraph')),
                ('paragraph_2', models.TextField(blank=True, default='Our team combines technical expertise with artistic sensibility. Every image that passes through our hands receives the same meticulous attention — whether it is a simple background removal or a complex ghost mannequin composite.', help_text='Second story paragraph')),
                ('paragraph_3', models.TextField(blank=True, default='We believe that great imagery is not a luxury — it is a necessity for brands that want to stand out. That is why we have built our entire workflow around quality, speed, and reliability.', help_text='Third story paragraph')),
                ('featured_image', models.ImageField(blank=True, help_text='Optional image for right side (replaces default icon)', null=True, upload_to='about/story/')),
                ('featured_image_alt', models.CharField(blank=True, default='About PicPicxels', help_text='Alt text for featured image', max_length=200)),
                ('icon_name', models.CharField(blank=True, default='Target', help_text='Lucide icon name when no image is uploaded (e.g. Target, Compass, Award, Shield, Sparkles)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Story (Who We Are)',
                'verbose_name_plural': 'Company Story (Who We Are)',
            },
        ),
    ]
