# Generated by Django 5.2.15 on 2026-09-12 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0066_aboutstorysection'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Privacy Policy', help_text='Hero title', max_length=200)),
                ('hero_subtitle', models.TextField(default='Your privacy matters to us. This policy explains how PicPicxels collects, uses, and protects your personal information when you use our platform and services.', help_text='Hero description')),
                ('last_updated', models.CharField(default='August 2026', help_text='e.g. August 2026', max_length=100)),
                ('intro_text', models.TextField(default='This Privacy Policy describes how PicPicxels Inc. collects, uses, and shares your personal information. By using our platform, you consent to the practices described in this policy.', help_text='Introductory paragraph before the policy sections')),
                ('dpo_name', models.CharField(default='PicPicxels Privacy Team', help_text='Data Protection Officer / Team name', max_length=200)),
                ('dpo_email', models.CharField(default='info@picpicxels.com', help_text='Contact email for privacy', max_length=200)),
                ('dpo_response_time', models.CharField(default='We respond to all privacy inquiries within 30 days', help_text='Expected response time', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Privacy Policy Page',
                'verbose_name_plural': 'Privacy Policy Page',
            },
        ),
        migrations.CreateModel(
            name='TermsConditionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Terms & Conditions', help_text='Hero title', max_length=200)),
                ('hero_subtitle', models.TextField(default='Please read these terms carefully before using our platform. They govern your relationship with PicPicxels and outline both your rights and responsibilities.', help_text='Hero description')),
                ('last_updated', models.CharField(default='August 2026', help_text='e.g. August 2026', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Terms & Conditions Page',
                'verbose_name_plural': 'Terms & Conditions Page',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Section title (e.g. Information We Collect)', max_length=255)),
                ('icon_name', models.CharField(blank=True, default='Shield', help_text='Lucide icon name (e.g. Eye, Lock, Shield, UserCheck, Cookie, Mail, FileText)', max_length=100)),
                ('content', models.TextField(help_text='Section content in HTML or plain text (supports <p>, <ul>, <li>, <strong>, etc.)')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cms.privacypolicypage')),
            ],
            options={
                'verbose_name': 'Privacy Policy Section',
                'verbose_name_plural': 'Privacy Policy Sections',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Stat value (e.g. AES-256, SOC 2, GDPR, 0)', max_length=100)),
                ('label', models.CharField(help_text='Stat label (e.g. Encryption Standard, Type II Compliant)', max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='cms.privacypolicypage')),
            ],
            options={
                'verbose_name': 'Privacy Stat Card',
                'verbose_name_plural': 'Privacy Stat Cards',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TermsClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Clause title (e.g. Acceptance of Terms)', max_length=255)),
                ('anchor_id', models.CharField(blank=True, help_text='URL anchor identifier (e.g. acceptance, use-of-service, etc.)', max_length=100)),
                ('content', models.TextField(help_text='Clause content in HTML or plain text (supports <p>, <ul>, <li>, <strong>, etc.)')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='cms.termsconditionpage')),
            ],
            options={
                'verbose_name': 'Terms Clause',
                'verbose_name_plural': 'Terms Clauses',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TermsHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='01', help_text='Badge number (e.g. 01, 02)', max_length=20)),
                ('title', models.CharField(help_text='Highlight title (e.g. Fair Usage)', max_length=200)),
                ('description', models.TextField(help_text='Short description')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='cms.termsconditionpage')),
            ],
            options={
                'verbose_name': 'Terms Highlight Card',
                'verbose_name_plural': 'Terms Highlight Cards',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
