# Generated by Django 5.2.15 on 2026-09-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0067_privacypolicypage_termsconditionpage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='is_pricing_faq',
            field=models.BooleanField(default=False, help_text='Show this FAQ on the Pricing page'),
        ),
    ]
