# Generated by Django 5.2.15 on 2026-09-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0068_faq_is_pricing_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='model_3d_embed_url',
            field=models.TextField(blank=True, default='', help_text='Paste Sketchfab / Spline / 3D iframe embed URL or full <iframe> code'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='model_3d_file',
            field=models.FileField(blank=True, help_text='Or upload a 3D model file (.glb, .gltf)', null=True, upload_to='hero/3d/'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='model_3d_title',
            field=models.CharField(blank=True, default='', help_text='Optional title for the 3D model (e.g. "01. Modern Chair")', max_length=200),
        ),
        migrations.AddField(
            model_name='herosection',
            name='visual_type',
            field=models.CharField(choices=[('slider', 'Image Slider'), ('3d', '3D Model Viewer')], default='slider', help_text='Choose between standard Image Slider or interactive 3D Model Viewer', max_length=20),
        ),
    ]
