# Generated by Django 5.2.15 on 2026-09-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0069_herosection_model_3d_embed_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended Size: 1600 × 1200 px\nAspect Ratio: 4:3 (rendered as aspect-ratio: 4/3)\nDisplay Usage: Homepage Hero Slider (Hero.tsx)\nRendering: object-fit: cover, overflow: hidden\nDesktop: 2-column grid layout\nTablet (<=992px): Single column, max-width 520px\nMobile (<=576px): Full width with reduced padding\nSafe Area: Keep important content within center 70%\n  — Image is cropped on all viewports via overflow:hidden', null=True, upload_to='hero/slides/'),
        ),
    ]
