# Generated by Django 5.2.15 on 2026-09-26 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0070_alter_heroslide_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField(help_text='Did the reader find this article helpful?')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Rating from 1 to 5 stars', null=True)),
                ('comment', models.TextField(blank=True, default='', help_text='Reader comment or suggestion')),
                ('user_name', models.CharField(blank=True, default='', max_length=150)),
                ('user_email', models.EmailField(blank=True, default='', max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(help_text='The blog post this feedback is for', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='cms.blogpost')),
            ],
            options={
                'verbose_name': 'Blog Feedback',
                'verbose_name_plural': 'Blog Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
