# Generated by Django 5.2.15 on 2026-09-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0071_blogfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='canonical_url',
            field=models.URLField(blank=True, default='', help_text='Custom canonical URL (defaults to https://www.picpicxels.com/services/<slug>)'),
        ),
        migrations.AddField(
            model_name='service',
            name='custom_schema',
            field=models.TextField(blank=True, default='', help_text='Paste custom JSON-LD schema (valid JSON object or @graph array). Overrides default schema if set.'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_keywords',
            field=models.CharField(blank=True, default='', help_text='Comma-separated SEO keywords', max_length=500),
        ),
        migrations.AddField(
            model_name='service',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Social share / OpenGraph image (1200x630 recommended)', null=True, upload_to='services/og/'),
        ),
        migrations.AddField(
            model_name='service',
            name='schema_type',
            field=models.CharField(choices=[('Service', 'Service (Standard)'), ('ProfessionalService', 'ProfessionalService'), ('Product', 'Product / Package'), ('custom', 'Custom JSON-LD')], default='Service', help_text='Schema.org type for this service', max_length=50),
        ),
    ]
