# Generated by Django 5.2.15 on 2026-10-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0072_service_canonical_url_service_custom_schema_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category title, e.g. Clothing / Apparel', max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly slug, e.g. clothing', max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display sort order')),
                ('is_active', models.BooleanField(default=True, help_text='Display in Free Trial / Order form')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='page',
            name='custom_schema',
            field=models.TextField(blank=True, default='', help_text='Custom JSON-LD structured data (paste valid JSON object, without script tags)'),
        ),
    ]
