# Generated by Django 6.0.5 on 2026-06-27 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuideCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Guide Category',
                'verbose_name_plural': 'Guide Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=550, unique=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='guides/')),
                ('featured_image_alt', models.CharField(blank=True, default='', max_length=500)),
                ('short_description', models.TextField(blank=True, default='')),
                ('full_content', models.TextField(blank=True, default='')),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, default='', max_length=500)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guides', to='guides.guidecategory')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
