# Generated by Django 5.2.15 on 2026-07-16 06:03

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guide',
            options={'ordering': ['sort_order', '-created_at'], 'verbose_name': 'Guide', 'verbose_name_plural': 'Guides'},
        ),
        migrations.AddField(
            model_name='guide',
            name='author',
            field=models.CharField(blank=True, default='', help_text='Name of the author or content creator.', max_length=300),
        ),
        migrations.AddField(
            model_name='guide',
            name='canonical_url',
            field=models.URLField(blank=True, default='', help_text='Optional canonical URL if this content is syndicated elsewhere.', max_length=500),
        ),
        migrations.AddField(
            model_name='guide',
            name='featured_image_caption',
            field=models.CharField(blank=True, default='', help_text='Optional caption displayed below the featured image.', max_length=500),
        ),
        migrations.AddField(
            model_name='guide',
            name='hero_badge_text',
            field=models.CharField(blank=True, default='', help_text='Optional badge text displayed above the title (e.g. "New" or "Updated").', max_length=200),
        ),
        migrations.AddField(
            model_name='guide',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='', help_text='Optional subtitle displayed below the title in the hero section.'),
        ),
        migrations.AddField(
            model_name='guide',
            name='meta_keywords',
            field=models.TextField(blank=True, default='', help_text='Comma-separated keywords for SEO (e.g. "guide, tutorial, CGI, product rendering").'),
        ),
        migrations.AddField(
            model_name='guide',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Optional Open Graph image for social sharing. Recommended: 1200×630px.', null=True, upload_to='guides/og/'),
        ),
        migrations.AddField(
            model_name='guide',
            name='reading_time',
            field=models.IntegerField(blank=True, help_text='Estimated reading time in minutes. Auto-calculated from content if left blank.', null=True),
        ),
        migrations.AddField(
            model_name='guidecategory',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Brief description of this category (for internal reference).'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Select a category for this guide.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guides', to='guides.guidecategory'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='featured',
            field=models.BooleanField(default=False, help_text='Show this guide in the featured section.'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Upload a featured image. Recommended size: 1600×900px (16:9 ratio).', null=True, upload_to='guides/'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='featured_image_alt',
            field=models.CharField(blank=True, default='', help_text='Descriptive alt text for the featured image (important for accessibility and SEO).', max_length=500),
        ),
        migrations.AlterField(
            model_name='guide',
            name='full_content',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Write the full guide content here. Use Heading 2 and Heading 3 for sections — these are automatically used to generate the Table of Contents.'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Make this guide visible on the website.'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='meta_description',
            field=models.TextField(blank=True, default='', help_text='Meta description for search engine result pages.'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='meta_title',
            field=models.CharField(blank=True, default='', help_text='Custom title tag for search engines. Defaults to the guide title if left blank.', max_length=500),
        ),
        migrations.AlterField(
            model_name='guide',
            name='publish_date',
            field=models.DateField(blank=True, help_text='The date this guide was published. Auto-set to today when first published.', null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='short_description',
            field=models.TextField(blank=True, default='', help_text='A brief excerpt shown on listing cards and in search results.'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier. Auto-generated from title if left blank.', max_length=550, unique=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Display order (lower numbers appear first).'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='title',
            field=models.CharField(help_text='The title of the guide.', max_length=500),
        ),
    ]
