# Generated by Django 5.2.15 on 2026-07-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_alter_guide_options_guide_author_guide_canonical_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Show this guide in the featured section.'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, help_text='Make this guide visible on the website.'),
        ),
        migrations.AlterField(
            model_name='guidecategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
