# Generated by Django 6.0.5 on 2026-06-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('new_order', 'New Order'), ('contact_inquiry', 'Contact Inquiry'), ('quote_request', 'Quote Request'), ('support_message', 'Support Message'), ('payment_completed', 'Payment Completed'), ('payment_failed', 'Payment Failed'), ('refund_requested', 'Refund Requested'), ('user_registration', 'User Registration'), ('user_update', 'User Account Update'), ('settings_updated', 'Settings Updated'), ('backup_completed', 'Backup Completed'), ('security_alert', 'Security Alert'), ('system', 'System Notification')], default='system', max_length=30)),
                ('related_id', models.CharField(blank=True, help_text='ID of the related object (order, user, etc.)', max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
