# Generated by Django 5.2.15 on 2026-09-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('contact_inquiry', 'Contact Us Inquiry'), ('free_trial', 'Free Trial Request'), ('new_order', 'New Order'), ('quote_request', 'Quote Request'), ('support_message', 'Support Message'), ('payment_completed', 'Payment Completed'), ('payment_failed', 'Payment Failed'), ('refund_requested', 'Refund Requested'), ('user_registration', 'User Registration'), ('user_update', 'User Account Update'), ('settings_updated', 'Settings Updated'), ('backup_completed', 'Backup Completed'), ('security_alert', 'Security Alert'), ('system', 'System Notification')], default='system', max_length=30),
        ),
    ]
