# Generated by Django 5.2.15 on 2026-09-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text='Enable or disable automated email sending globally.')),
                ('smtp_host', models.CharField(default='smtp.gmail.com', help_text='SMTP server host (e.g. smtp.gmail.com for Google / Gmail)', max_length=255)),
                ('smtp_port', models.IntegerField(default=587, help_text='SMTP port (typically 587 for TLS, or 465 for SSL)')),
                ('smtp_use_tls', models.BooleanField(default=True, help_text='Use TLS connection (recommended for port 587)')),
                ('smtp_use_ssl', models.BooleanField(default=False, help_text='Use SSL connection (recommended for port 465)')),
                ('smtp_user', models.CharField(blank=True, help_text='Google/Gmail account email address (e.g. yourstudio@gmail.com)', max_length=255)),
                ('smtp_password', models.CharField(blank=True, help_text='Google App Password (16-letter App Password generated in Google Account > Security > 2-Step Verification > App Passwords)', max_length=255)),
                ('from_name', models.CharField(default='PicPixels', help_text="Sender display name (e.g. 'PicPixels Retouching Studio')", max_length=150)),
                ('from_email', models.EmailField(blank=True, help_text='From email address. If empty, smtp_user will be used.', max_length=254)),
                ('admin_emails', models.TextField(blank=True, default='', help_text='Recipient email addresses for admin notification alerts. Enter multiple emails separated by commas or new lines.')),
                ('notify_admins_on_order', models.BooleanField(default=True, help_text='Send email alert to all admin emails when a new Order Request is submitted.')),
                ('notify_admins_on_trial', models.BooleanField(default=True, help_text='Send email alert to all admin emails when a Free Trial is requested.')),
                ('notify_admins_on_contact', models.BooleanField(default=True, help_text='Send email alert to all admin emails when a Contact Us message is received.')),
                ('auto_reply_to_clients', models.BooleanField(default=True, help_text='Send automated confirmation/acknowledgement email to clients upon submission.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email & SMTP Configuration',
                'verbose_name_plural': 'Email & SMTP Configuration',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('client_order_request', 'Client Auto-Reply: Order Request Confirmation'), ('client_free_trial', 'Client Auto-Reply: Free Trial Confirmation'), ('client_contact_inquiry', 'Client Auto-Reply: Contact Us Confirmation'), ('admin_order_alert', 'Admin Alert: New Order Request Received'), ('admin_trial_alert', 'Admin Alert: New Free Trial Received'), ('admin_contact_alert', 'Admin Alert: New Contact Us Message')], help_text='Type of email notification', max_length=40, unique=True)),
                ('subject', models.CharField(help_text='Email subject line. Supports variables like {client_name}, {service_name}, {site_name}, {order_id}', max_length=255)),
                ('body_html', models.TextField(help_text='HTML email content. Supports dynamic variables: {client_name}, {client_email}, {client_phone}, {service_name}, {package_price}, {country}, {company_name}, {order_id}, {requirements}, {drive_link}, {site_name}, {support_email}, {admin_link}')),
                ('body_text', models.TextField(blank=True, help_text='Plain text fallback for email clients that do not support HTML')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this email template is active')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['template_type'],
            },
        ),
    ]
