# Generated by Django 5.2.15 on 2026-09-11 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_emailconfiguration_emailtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotificationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Admin recipient email address', max_length=254)),
                ('name', models.CharField(blank=True, default='', help_text="Name or role of this admin (e.g. 'Rohan - Founder', 'Support Lead')", max_length=150)),
                ('is_active', models.BooleanField(default=True, help_text='Enable or pause sending notification emails to this address')),
                ('notify_on_order', models.BooleanField(default=True, help_text='Receive alerts when a client submits an Order Request')),
                ('notify_on_trial', models.BooleanField(default=True, help_text='Receive alerts when a client requests a Free Trial')),
                ('notify_on_contact', models.BooleanField(default=True, help_text='Receive alerts when a client submits a Contact Us message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_config', models.ForeignKey(blank=True, help_text='Associated Email Configuration', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_emails', to='notifications.emailconfiguration')),
            ],
            options={
                'verbose_name': 'Admin Notification Email',
                'verbose_name_plural': 'Admin Notification Emails',
                'ordering': ['-created_at'],
            },
        ),
    ]
