# Generated by Django 6.0.5 on 2026-05-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('image_editing', 'Image Editing'), ('cgi_3d', 'CGI & 3D Modeling'), ('ai_models', 'AI Fashion Models'), ('video_editing', 'Video Editing')], default='image_editing', max_length=30),
        ),
    ]
