# Generated by Django 5.2.15 on 2026-07-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('image_editing', 'Image Editing'), ('cgi_3d', 'CGI & 3D Modeling'), ('ai_models', 'AI Fashion Models'), ('video_editing', 'Video Editing')], db_index=True, default='image_editing', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval / Payment'), ('in_progress', 'In Progress'), ('review', 'In Review by Client'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('retouching', 'Retouching'), ('quality_check', 'Quality Check'), ('review_pending', 'Review Pending'), ('approved', 'Approved'), ('rejected', 'Rejected / Needs Revision')], db_index=True, default='uploaded', max_length=30),
        ),
    ]
