# Generated by Django 6.0.5 on 2026-06-01 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, help_text='Internal path or external URL', max_length=500)),
                ('location', models.CharField(choices=[('header', 'Header'), ('footer', 'Footer'), ('mega_menu', 'Mega Menu')], default='header', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('opens_in_new_tab', models.BooleanField(default=False)),
                ('icon', models.CharField(blank=True, help_text='Material icon name', max_length=50)),
                ('css_class', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='navigation.navigationitem')),
            ],
            options={
                'verbose_name': 'Navigation Item',
                'verbose_name_plural': 'Navigation Items',
                'ordering': ['location', 'parent_id', 'order'],
            },
        ),
    ]
