# Generated by Django 6.0.5 on 2026-06-19 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seosetting',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200×630px (1.91:1). Max 300KB. Open Graph social share image.', null=True, upload_to='seo/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Recommended: 32×32px or 96×96px (1:1). Max 50KB. Browser tab icon. ICO or PNG.', null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, help_text='Recommended: 300×80px, transparent PNG preferred. Max 100KB. Site header logo.', null=True, upload_to='site/'),
        ),
    ]
