# Generated by Django 6.0.5 on 2026-06-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_alter_seosetting_og_image_alter_sitesetting_favicon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seosetting',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200×630px (1.91:1 landscape). Format: JPG or PNG. Max 300KB. Open Graph image used when the page is shared on Facebook, LinkedIn, and other social platforms.', null=True, upload_to='seo/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Recommended: 32×32px or 96×96px (1:1 square). Format: ICO or PNG. Max 50KB. Browser tab icon / favicon. Smallest readable size preferred.', null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, help_text='Recommended: 300×80px. Format: transparent PNG or SVG preferred. Max 100KB. Main site logo displayed in the site header navigation bar.', null=True, upload_to='site/'),
        ),
    ]
