# Generated by Django 6.0.5 on 2026-06-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_alter_seosetting_og_image_alter_sitesetting_favicon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seosetting',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Use 1.91:1 landscape ratio (1200×630px output). This exact ratio is enforced by Facebook, LinkedIn, and Slack previews. The image will NOT be cropped — it fills a fixed social card area. Ensure text and branding fit within the center 80% to avoid clipping in chat/embed views. Minimum width: 1200px.', null=True, upload_to='seo/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Use 1:1 square icon. Served as the browser tab icon and bookmark image. Browsers request 16×16, 32×32, and 48×48 automatically. A 96×96 source ensures crisp rendering at all sizes. Use ICO or PNG format. Keep the design extremely simple.', null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, help_text='Use transparent-background logo (PNG or SVG preferred). Displayed in the site header navigation bar. Height is fixed (36px); width scales proportionally. A horizontal/landscape logo layout works best. If using PNG, minimum height: 72px (2× display).', null=True, upload_to='site/'),
        ),
    ]
