# Generated by Django 6.0.5 on 2026-06-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_alter_seosetting_og_image_alter_sitesetting_favicon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seosetting',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200x630px (1.91:1). Used for Facebook, LinkedIn, and Slack previews. Text and branding should stay within center 80%.', null=True, upload_to='seo/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Recommended: 96x96px (1:1 square, ICO or PNG). Used as browser tab icon and bookmark image. Keep design extremely simple for small sizes.', null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, help_text='Recommended: SVG or transparent PNG (min 72px height). Used in site header navigation bar. Horizontal / landscape layout works best.', null=True, upload_to='site/'),
        ),
    ]
