# Generated by Django 6.0.5 on 2026-06-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_alter_seosetting_og_image_alter_sitesetting_favicon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seosetting',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Recommended Size: 1200 × 630 px\nAspect Ratio: 1.91:1\nDisplay Usage: Facebook / LinkedIn / Slack / Discord link previews\nSafe Area: Keep text and branding within center 80%\n  — Twitter/X previews may crop top/bottom\n  — Minimum: 600 × 315 px; Maximum: 1200 × 630 px', null=True, upload_to='seo/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Recommended Size: 96 × 96 px (1:1 square)\nFormat: ICO or PNG\nDisplay Usage: Browser tab icon, bookmark favicon\nSafe Area: Entire area — designs must be legible at 16px\n  — Keep design extremely simple with high contrast', null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, help_text='Recommended Size: SVG preferred, PNG min 144 × 72 px\nAspect Ratio: Landscape / horizontal (no fixed ratio)\nDisplay Usage: Site logo in header + footer\nHeader: height: 36px, object-fit: contain\nFooter: intrinsic dimensions\nFORMAT: SVG strongly preferred for crisp rendering at all sizes\n  — PNG/JPG may appear pixelated on retina displays', null=True, upload_to='site/'),
        ),
    ]
