# Generated by Django 6.0.5 on 2026-06-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_alter_seosetting_og_image_alter_sitesetting_favicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seosetting',
            name='og_image_alt',
            field=models.CharField(blank=True, help_text='Alt text for the OG image', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='favicon_alt',
            field=models.CharField(blank=True, help_text='Alt text for the favicon', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='logo_alt',
            field=models.CharField(blank=True, help_text='Alt text for the site logo', max_length=200),
        ),
    ]
