# Generated by Django 5.2.15 on 2026-09-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0007_seosetting_og_image_alt_sitesetting_favicon_alt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='custom_body_end_scripts',
            field=models.TextField(blank=True, default='', help_text='Custom scripts to inject before </body> closing tag (e.g. chat widgets, analytics)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='custom_body_start_scripts',
            field=models.TextField(blank=True, default='', help_text='Custom scripts to inject immediately after <body> opening tag (e.g. GTM noscript)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='custom_head_scripts',
            field=models.TextField(blank=True, default='', help_text='Custom scripts/tags to inject inside <head> (e.g. tracking scripts, meta tags)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='facebook_pixel_id',
            field=models.CharField(blank=True, default='', help_text='Meta / Facebook Pixel ID (e.g. 123456789012345)', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='google_analytics_id',
            field=models.CharField(blank=True, default='', help_text='Google Analytics 4 Measurement ID (e.g. G-XXXXXXXXXX)', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='google_search_console_code',
            field=models.CharField(blank=True, default='', help_text='Google Search Console verification code or meta tag content', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='google_tag_manager_id',
            field=models.CharField(blank=True, default='', help_text='Google Tag Manager Container ID (e.g. GTM-XXXXXXX)', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='organization_schema',
            field=models.TextField(blank=True, default='', help_text='Global Organization / LocalBusiness JSON-LD Schema (leave empty for auto-generated schema)'),
        ),
    ]
