# Generated by Django 5.2.15 on 2026-09-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0008_sitesetting_custom_body_end_scripts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='bd_office_address',
            field=models.TextField(blank=True, default='71&45, House, Road-28, Dhaka 1230, Bangladesh', help_text='Physical address for Bangladesh office'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bd_office_email',
            field=models.CharField(blank=True, default='info@picpixels.com', help_text='Email address for Bangladesh office', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bd_office_phone',
            field=models.CharField(blank=True, default='+880 1622915832', help_text='Phone number for Bangladesh office', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bd_office_title',
            field=models.CharField(default='Production House – Bangladesh', help_text='Title for Bangladesh production house', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_location_title',
            field=models.CharField(default='Location Based Services', help_text='Title for location services widget in footer', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_locations',
            field=models.TextField(blank=True, default='Texas\nCalifornia\nFlorida\nNew York', help_text='Locations list (one per line). Format: "Location Name" or "Location Name | /services?location=slug"'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='usa_office_address',
            field=models.TextField(blank=True, default='3150 Roswell Rd. NW #1004, Atlanta, GA 30305, USA', help_text='Physical address for USA office'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='usa_office_email',
            field=models.CharField(blank=True, default='info@picpixels.com', help_text='Email address for USA office', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='usa_office_phone',
            field=models.CharField(blank=True, default='+1 409 419 3704', help_text='Phone number for USA office', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='usa_office_title',
            field=models.CharField(default='Corporate Office – USA', help_text='Title for USA corporate office', max_length=150),
        ),
    ]
