# Generated by Django 5.2.15 on 2026-09-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0009_sitesetting_bd_office_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='bd_office_title',
            field=models.CharField(blank=True, default='Production House – Bangladesh', help_text='Title for Bangladesh production house (optional, leave blank to hide)', max_length=150),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='usa_office_title',
            field=models.CharField(blank=True, default='Corporate Office – USA', help_text='Title for USA corporate office (optional, leave blank to hide)', max_length=150),
        ),
    ]
