# Generated by Django 5.2.15 on 2026-09-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0010_alter_sitesetting_bd_office_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='recaptcha_enabled',
            field=models.BooleanField(default=False, help_text='Enable Google reCAPTCHA bot protection on public forms (Contact, Free Trial)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='recaptcha_secret_key',
            field=models.CharField(blank=True, default='', help_text='Google reCAPTCHA Secret Key (kept private on server)', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='recaptcha_site_key',
            field=models.CharField(blank=True, default='', help_text='Google reCAPTCHA v2/v3 Site Key (public)', max_length=255),
        ),
    ]
