# Generated by Django 5.2.15 on 2026-10-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0011_sitesetting_recaptcha_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='business_hours',
            field=models.TextField(blank=True, default='Mon – Fri: 9:00 AM – 6:00 PM\nSat: 10:00 AM – 4:00 PM', help_text='Business hours displayed on contact and demo pages (one per line, e.g. "Mon – Fri: 9:00 AM – 6:00 PM\\nSat: 10:00 AM – 4:00 PM")'),
        ),
    ]
