# Generated by Django 5.2.15 on 2026-07-09 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Case Study Tag',
                'verbose_name_plural': 'Case Study Tags',
            },
        ),
        migrations.AddField(
            model_name='casestudy',
            name='challenges',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='industry',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='process_workflow',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='project_duration',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='project_overview',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='results',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='services_provided',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='solution',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='technologies_used',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='CaseStudyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='case_studies/gallery/')),
                ('alt_text', models.CharField(blank=True, default='', max_length=500)),
                ('sort_order', models.IntegerField(default=0)),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='case_studies.casestudy')),
            ],
            options={
                'verbose_name': 'Case Study Gallery Image',
                'verbose_name_plural': 'Case Study Gallery Images',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='casestudy',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='case_studies', to='case_studies.casestudytag'),
        ),
    ]
