# Generated by Django 5.2.15 on 2026-07-10 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0002_casestudytag_casestudy_challenges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='brand_values',
            field=models.TextField(blank=True, default='', help_text='Brand values, mission, vision'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='canonical_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='client_logo',
            field=models.ImageField(blank=True, null=True, upload_to='case_studies/clients/'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='country',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='excerpt',
            field=models.TextField(blank=True, default='', help_text='Short summary shown in listing cards'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='hero_banner',
            field=models.ImageField(blank=True, help_text='Large hero background image', null=True, upload_to='case_studies/hero/'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='hero_banner_alt',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='introduction',
            field=models.TextField(blank=True, default='', help_text='Opening paragraph for the detail page hero'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='case_studies/og/'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='project_goals',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='reading_time',
            field=models.IntegerField(default=0, help_text='Estimated reading time in minutes'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='scope_of_work',
            field=models.JSONField(blank=True, default=list, help_text='Array of scope items e.g. ["Hero renders", "Lifestyle renders"]'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='statistics',
            field=models.JSONField(blank=True, default=list, help_text='Array of {value, label, suffix} objects'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='casestudyimage',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.CreateModel(
            name='CaseStudyTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=300)),
                ('author_role', models.CharField(blank=True, default='', max_length=300)),
                ('company', models.CharField(blank=True, default='', max_length=300)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='case_studies/testimonials/')),
                ('quote', models.TextField()),
                ('rating', models.IntegerField(default=5, help_text='1-5 stars')),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='case_studies.casestudy')),
            ],
            options={
                'verbose_name': 'Case Study Testimonial',
                'verbose_name_plural': 'Case Study Testimonials',
            },
        ),
    ]
