# Generated by Django 5.2.15 on 2026-07-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0003_casestudy_brand_values_casestudy_canonical_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='scope_of_work',
            field=models.JSONField(blank=True, default=list, help_text='Array of scope items e.g. ["Hero renders", "Lifestyle renders"]', null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='statistics',
            field=models.JSONField(blank=True, default=list, help_text='Array of {value, label, suffix} objects', null=True),
        ),
    ]
