# Generated by Django 5.2.15 on 2026-07-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0004_alter_casestudy_scope_of_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='casestudycategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
