# Generated by Django 5.2.15 on 2026-09-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0005_add_db_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='custom_schema',
            field=models.TextField(blank=True, default='', help_text='Paste custom JSON-LD schema (valid JSON object or @graph array). Overrides default schema if set.'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='meta_keywords',
            field=models.CharField(blank=True, default='', help_text='Comma-separated SEO keywords', max_length=500),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='schema_type',
            field=models.CharField(choices=[('Article', 'Article (Standard)'), ('TechArticle', 'TechArticle / Case Study'), ('CreativeWork', 'CreativeWork'), ('custom', 'Custom JSON-LD')], default='Article', help_text='Schema.org type for this case study', max_length=50),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='canonical_url',
            field=models.URLField(blank=True, default='', help_text='Custom canonical URL (defaults to https://www.picpicxels.com/case-studies/<slug>)'),
        ),
    ]
