# Generated by Django 6.0.5 on 2026-06-15 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_service_portfolio_client_portfolio_completion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='after_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/after/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='before_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/before/'),
        ),
        migrations.CreateModel(
            name='PortfolioComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_image', models.ImageField(upload_to='portfolio/before/')),
                ('after_image', models.ImageField(upload_to='portfolio/after/')),
                ('label', models.CharField(blank=True, help_text='Optional label (e.g. "Retouching Result")', max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'Before/After Pair',
                'verbose_name_plural': 'Before/After Pairs',
                'ordering': ['sort_order'],
            },
        ),
    ]
