# Generated by Django 6.0.5 on 2026-06-19 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolio_after_image_portfolio_before_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='after_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200×900px (4:3). Max 500KB. Before/after comparison in portfolio.', null=True, upload_to='portfolio/after/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='before_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200×900px (4:3). Max 500KB. Before/after comparison in portfolio.', null=True, upload_to='portfolio/before/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200×900px (4:3). Max 500KB. Portfolio grid card thumbnail.', null=True, upload_to='portfolio/'),
        ),
        migrations.AlterField(
            model_name='portfoliocomparison',
            name='after_image',
            field=models.ImageField(help_text='Recommended: 1200×900px (4:3). Max 500KB. Before/after comparison in portfolio.', upload_to='portfolio/after/'),
        ),
        migrations.AlterField(
            model_name='portfoliocomparison',
            name='before_image',
            field=models.ImageField(help_text='Recommended: 1200×900px (4:3). Max 500KB. Before/after comparison in portfolio.', upload_to='portfolio/before/'),
        ),
        migrations.AlterField(
            model_name='portfoliogallery',
            name='image',
            field=models.ImageField(help_text='Recommended: 1200×900px (4:3). Max 500KB. Portfolio gallery image.', upload_to='portfolio/gallery/'),
        ),
    ]
