# Generated by Django 6.0.5 on 2026-06-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_portfolio_after_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='after_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200×900px (4:3). Format: JPG or PNG. Max 500KB. Before/after comparison images in portfolio detail. Both images must match dimensions exactly.', null=True, upload_to='portfolio/after/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='before_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200×900px (4:3). Format: JPG or PNG. Max 500KB. Before/after comparison images in portfolio detail. Both images must match dimensions exactly.', null=True, upload_to='portfolio/before/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200×900px (4:3). Format: JPG or WebP. Max 500KB. Featured image / thumbnail for portfolio grid cards.', null=True, upload_to='portfolio/'),
        ),
        migrations.AlterField(
            model_name='portfoliocomparison',
            name='after_image',
            field=models.ImageField(help_text='Recommended: 1200×900px (4:3). Format: JPG or PNG. Max 500KB. Before/after comparison images in portfolio detail. Both images must match dimensions exactly.', upload_to='portfolio/after/'),
        ),
        migrations.AlterField(
            model_name='portfoliocomparison',
            name='before_image',
            field=models.ImageField(help_text='Recommended: 1200×900px (4:3). Format: JPG or PNG. Max 500KB. Before/after comparison images in portfolio detail. Both images must match dimensions exactly.', upload_to='portfolio/before/'),
        ),
        migrations.AlterField(
            model_name='portfoliogallery',
            name='image',
            field=models.ImageField(help_text='Recommended: 1200×900px (4:3). Format: JPG or WebP. Max 500KB. Portfolio gallery image shown in the lightbox/grid on portfolio detail pages.', upload_to='portfolio/gallery/'),
        ),
    ]
