# Generated by Django 6.0.5 on 2026-06-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_portfolio_after_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='after_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200×800px (3:2). Format: JPG or PNG. Max 500KB. Upload paired images with same lighting and angle for accurate comparison slider.', null=True, upload_to='portfolio/after/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='before_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200×800px (3:2). Format: JPG or PNG. Max 500KB. Upload paired images with same lighting and angle for accurate comparison slider.', null=True, upload_to='portfolio/before/'),
        ),
        migrations.AlterField(
            model_name='portfoliocomparison',
            name='after_image',
            field=models.ImageField(help_text='Recommended: 1200×800px (3:2). Format: JPG or PNG. Max 500KB. Upload paired images with same lighting and angle for accurate comparison slider.', upload_to='portfolio/after/'),
        ),
        migrations.AlterField(
            model_name='portfoliocomparison',
            name='before_image',
            field=models.ImageField(help_text='Recommended: 1200×800px (3:2). Format: JPG or PNG. Max 500KB. Upload paired images with same lighting and angle for accurate comparison slider.', upload_to='portfolio/before/'),
        ),
        migrations.AlterField(
            model_name='portfoliogallery',
            name='image',
            field=models.ImageField(help_text='Recommended: 1200×800px (3:2). Format: JPG or WebP. Max 500KB. Used in portfolio grid and detail view. Maintain consistent framing style.', upload_to='portfolio/gallery/'),
        ),
    ]
