# Generated by Django 6.0.5 on 2026-06-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_portfolio_after_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='after_image',
            field=models.ImageField(blank=True, help_text='CRITICAL: Both images must use IDENTICAL dimensions and aspect ratio. Use balanced landscape ratio (3:2 recommended). Same lighting, angle, and framing required for a smooth comparison slider experience. Even slight misalignment degrades the visual effect. Minimum width: 1200px.', null=True, upload_to='portfolio/after/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='before_image',
            field=models.ImageField(blank=True, help_text='CRITICAL: Both images must use IDENTICAL dimensions and aspect ratio. Use balanced landscape ratio (3:2 recommended). Same lighting, angle, and framing required for a smooth comparison slider experience. Even slight misalignment degrades the visual effect. Minimum width: 1200px.', null=True, upload_to='portfolio/before/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Use balanced landscape composition (4:3). Featured thumbnail in the portfolio grid cards. Grid items use a fixed aspect ratio — images are cropped to fill. Ensure the main subject is centered and not near edges. Minimum width: 1200px.', null=True, upload_to='portfolio/'),
        ),
        migrations.AlterField(
            model_name='portfoliocomparison',
            name='after_image',
            field=models.ImageField(help_text='CRITICAL: Both images must use IDENTICAL dimensions and aspect ratio. Use balanced landscape ratio (3:2 recommended). Same lighting, angle, and framing required for a smooth comparison slider experience. Even slight misalignment degrades the visual effect. Minimum width: 1200px.', upload_to='portfolio/after/'),
        ),
        migrations.AlterField(
            model_name='portfoliocomparison',
            name='before_image',
            field=models.ImageField(help_text='CRITICAL: Both images must use IDENTICAL dimensions and aspect ratio. Use balanced landscape ratio (3:2 recommended). Same lighting, angle, and framing required for a smooth comparison slider experience. Even slight misalignment degrades the visual effect. Minimum width: 1200px.', upload_to='portfolio/before/'),
        ),
        migrations.AlterField(
            model_name='portfoliogallery',
            name='image',
            field=models.ImageField(help_text='Use balanced landscape composition (3:2 recommended). Displayed in a masonry/grid layout in portfolio detail view. Layout adapts between grid rows and stacked columns per screen. Maintain visual consistency across the set — similar framing and lighting creates a professional look. Minimum width: 1200px.', upload_to='portfolio/gallery/'),
        ),
    ]
