# Generated by Django 6.0.5 on 2026-06-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_portfolio_after_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='after_image',
            field=models.ImageField(blank=True, help_text='Used in comparison slider for transformation display. Both images must have identical framing, angle, and lighting for accurate comparison.', null=True, upload_to='portfolio/after/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='before_image',
            field=models.ImageField(blank=True, help_text='Used in comparison slider for transformation display. Both images must have identical framing, angle, and lighting for accurate comparison.', null=True, upload_to='portfolio/before/'),
        ),
        migrations.AlterField(
            model_name='portfoliocomparison',
            name='after_image',
            field=models.ImageField(help_text='Used in comparison slider for transformation display. Both images must have identical framing, angle, and lighting for accurate comparison.', upload_to='portfolio/after/'),
        ),
        migrations.AlterField(
            model_name='portfoliocomparison',
            name='before_image',
            field=models.ImageField(help_text='Used in comparison slider for transformation display. Both images must have identical framing, angle, and lighting for accurate comparison.', upload_to='portfolio/before/'),
        ),
        migrations.AlterField(
            model_name='portfoliogallery',
            name='image',
            field=models.ImageField(help_text='Used in portfolio grid and detail view. Ensure consistent style across all portfolio images for uniform gallery presentation.', upload_to='portfolio/gallery/'),
        ),
    ]
