# Generated by Django 6.0.5 on 2026-06-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_portfolio_after_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='after_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200x800px (3:2). Used in comparison slider for transformation display. Both images must have identical framing, angle, and lighting.', null=True, upload_to='portfolio/after/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='before_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200x800px (3:2). Used in comparison slider for transformation display. Both images must have identical framing, angle, and lighting.', null=True, upload_to='portfolio/before/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200x800px (3:2). Used as featured thumbnail in portfolio grid cards. Grid items use fixed aspect ratio — keep subject centered.', null=True, upload_to='portfolio/'),
        ),
        migrations.AlterField(
            model_name='portfoliocomparison',
            name='after_image',
            field=models.ImageField(help_text='Recommended: 1200x800px (3:2). Used in comparison slider for transformation display. Both images must have identical framing, angle, and lighting.', upload_to='portfolio/after/'),
        ),
        migrations.AlterField(
            model_name='portfoliocomparison',
            name='before_image',
            field=models.ImageField(help_text='Recommended: 1200x800px (3:2). Used in comparison slider for transformation display. Both images must have identical framing, angle, and lighting.', upload_to='portfolio/before/'),
        ),
        migrations.AlterField(
            model_name='portfoliogallery',
            name='image',
            field=models.ImageField(help_text='Recommended: 1200x800px (3:2). Used in portfolio grid and detail view. Keep consistent style across all portfolio images.', upload_to='portfolio/gallery/'),
        ),
    ]
