# Generated by Django 6.0.5 on 2026-06-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_portfolio_after_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='after_image',
            field=models.ImageField(blank=True, help_text='Recommended Size: 1600 × 1000 px\nAspect Ratio: 16:10 (aspect-ratio: 16/10, border-radius: 16px)\nDisplay Usage: Portfolio BEFORE/AFTER comparison (BeforeAfter.tsx)\nRendering: Two <img> elements, object-fit: cover, clip-path overlay\nInteractive slider: User drags handle to reveal comparison\nCRITICAL: Both images MUST have identical framing / angle / lighting\nSafe Area: Center 70% — slider reveals different portions\n  — Any mismatch in composition will be visually jarring', null=True, upload_to='portfolio/after/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='before_image',
            field=models.ImageField(blank=True, help_text='Recommended Size: 1600 × 1000 px\nAspect Ratio: 16:10 (aspect-ratio: 16/10, border-radius: 16px)\nDisplay Usage: Portfolio BEFORE/AFTER comparison (BeforeAfter.tsx)\nRendering: Two <img> elements, object-fit: cover, clip-path overlay\nInteractive slider: User drags handle to reveal comparison\nCRITICAL: Both images MUST have identical framing / angle / lighting\nSafe Area: Center 70% — slider reveals different portions\n  — Any mismatch in composition will be visually jarring', null=True, upload_to='portfolio/before/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Recommended Size: 1200 × 900 px\nAspect Ratio: 4:3 (aspect-ratio: 4/3)\nDisplay Usage: Portfolio grid card thumbnails (PortfolioGallery.tsx)\nRendering: object-fit: cover, overflow: hidden\nGrid: 5-col (>1199px) → 3-col (768-1199px) → 2-col (<=767px)\nHover: scale(1.08) transform\nSafe Area: Center 70%\n  — Consistent grid framing across all viewports', null=True, upload_to='portfolio/'),
        ),
        migrations.AlterField(
            model_name='portfoliocomparison',
            name='after_image',
            field=models.ImageField(help_text='Recommended Size: 1600 × 1000 px\nAspect Ratio: 16:10 (aspect-ratio: 16/10, border-radius: 16px)\nDisplay Usage: Portfolio BEFORE/AFTER comparison (BeforeAfter.tsx)\nRendering: Two <img> elements, object-fit: cover, clip-path overlay\nInteractive slider: User drags handle to reveal comparison\nCRITICAL: Both images MUST have identical framing / angle / lighting\nSafe Area: Center 70% — slider reveals different portions\n  — Any mismatch in composition will be visually jarring', upload_to='portfolio/after/'),
        ),
        migrations.AlterField(
            model_name='portfoliocomparison',
            name='before_image',
            field=models.ImageField(help_text='Recommended Size: 1600 × 1000 px\nAspect Ratio: 16:10 (aspect-ratio: 16/10, border-radius: 16px)\nDisplay Usage: Portfolio BEFORE/AFTER comparison (BeforeAfter.tsx)\nRendering: Two <img> elements, object-fit: cover, clip-path overlay\nInteractive slider: User drags handle to reveal comparison\nCRITICAL: Both images MUST have identical framing / angle / lighting\nSafe Area: Center 70% — slider reveals different portions\n  — Any mismatch in composition will be visually jarring', upload_to='portfolio/before/'),
        ),
        migrations.AlterField(
            model_name='portfoliogallery',
            name='image',
            field=models.ImageField(help_text='Recommended Size: 1200 × 900 px\nAspect Ratio: 4:3\nDisplay Usage: Portfolio detail gallery (PortfolioGallery.tsx)\nRendering: object-fit: cover, overflow: hidden\nSame grid behavior as portfolio featured\nSafe Area: Center 70%\n  — All gallery images share the same crop area', upload_to='portfolio/gallery/'),
        ),
    ]
