# Generated by Django 6.0.5 on 2026-06-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_portfolio_after_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='after_image_alt',
            field=models.CharField(blank=True, help_text='Alt text for the after image', max_length=200),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='before_image_alt',
            field=models.CharField(blank=True, help_text='Alt text for the before image', max_length=200),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='featured_image_alt',
            field=models.CharField(blank=True, help_text='Alt text for the featured image', max_length=200),
        ),
        migrations.AddField(
            model_name='portfoliocomparison',
            name='after_image_alt',
            field=models.CharField(blank=True, help_text='Alt text for the after image', max_length=200),
        ),
        migrations.AddField(
            model_name='portfoliocomparison',
            name='before_image_alt',
            field=models.CharField(blank=True, help_text='Alt text for the before image', max_length=200),
        ),
    ]
