# Generated by Django 6.0.5 on 2026-06-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_portfolio_after_image_alt_portfolio_before_image_alt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this category should be displayed on the frontend.'),
        ),
    ]
