# Generated by Django 6.0.5 on 2026-06-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_category_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliocomparison',
            name='after_image',
            field=models.ImageField(blank=True, help_text='Recommended Size: 1600 × 1000 px\nAspect Ratio: 16:10 (aspect-ratio: 16/10, border-radius: 16px)\nDisplay Usage: Portfolio BEFORE/AFTER comparison (BeforeAfter.tsx)\nRendering: Two <img> elements, object-fit: cover, clip-path overlay\nInteractive slider: User drags handle to reveal comparison\nCRITICAL: Both images MUST have identical framing / angle / lighting\nSafe Area: Center 70% — slider reveals different portions\n  — Any mismatch in composition will be visually jarring', null=True, upload_to='portfolio/after/'),
        ),
        migrations.AlterField(
            model_name='portfoliocomparison',
            name='before_image',
            field=models.ImageField(blank=True, help_text='Recommended Size: 1600 × 1000 px\nAspect Ratio: 16:10 (aspect-ratio: 16/10, border-radius: 16px)\nDisplay Usage: Portfolio BEFORE/AFTER comparison (BeforeAfter.tsx)\nRendering: Two <img> elements, object-fit: cover, clip-path overlay\nInteractive slider: User drags handle to reveal comparison\nCRITICAL: Both images MUST have identical framing / angle / lighting\nSafe Area: Center 70% — slider reveals different portions\n  — Any mismatch in composition will be visually jarring', null=True, upload_to='portfolio/before/'),
        ),
    ]
