# Generated by Django 5.2.15 on 2026-07-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_portfoliocomparison_after_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Show on homepage'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
