# Generated by Django 5.2.15 on 2026-09-11 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0062_pagecategory_blogpost_custom_schema_and_more'),
        ('portfolio', '0014_add_db_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioFAQ',
            fields=[
            ],
            options={
                'verbose_name': 'Portfolio FAQ',
                'verbose_name_plural': 'Portfolio FAQs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cms.faq',),
        ),
    ]
