# Generated by Django 5.2.15 on 2026-09-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_portfoliofaq'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='homepage_sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Tab order on the Home page (lowest number appears first).'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_on_homepage',
            field=models.BooleanField(db_index=True, default=True, help_text='Designates whether this category tab should be shown on the Home page portfolio section.'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='homepage_sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Display order on the Home page (lowest number first)'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='show_on_homepage',
            field=models.BooleanField(db_index=True, default=False, help_text='Explicitly show this portfolio item on the Home page portfolio showcase'),
        ),
    ]
