# Generated by Django 5.2.15 on 2026-09-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_category_homepage_sort_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Custom canonical URL (leave empty to use default)'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=300),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Custom OpenGraph image (1200x630)', null=True, upload_to='portfolio/og/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='schema_type',
            field=models.CharField(choices=[('CreativeWork', 'Creative Work'), ('VisualArtwork', 'Visual Artwork'), ('ImageGallery', 'Image Gallery'), ('Article', 'Article / Case Study')], default='CreativeWork', help_text='Schema.org structured data type', max_length=50),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO Meta Description (150-160 chars)'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO Meta Title (50-60 chars)', max_length=200),
        ),
    ]
