# Generated by Django 6.0.5 on 2026-05-21 06:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('file_format', models.CharField(choices=[('jpg', 'JPEG'), ('png', 'PNG'), ('tiff', 'TIFF'), ('psd', 'PSD')], default='png', max_length=20)),
                ('background_type', models.CharField(choices=[('transparent', 'Transparent'), ('white', 'White'), ('custom_hex', 'Custom Hex Color')], default='transparent', max_length=30)),
                ('background_color_hex', models.CharField(blank=True, max_length=7, null=True)),
                ('margin_percentage', models.IntegerField(default=10)),
                ('crop_width', models.IntegerField(blank=True, null=True)),
                ('crop_height', models.IntegerField(blank=True, null=True)),
                ('shadow_type', models.CharField(choices=[('none', 'No Shadow'), ('drop_shadow', 'Drop Shadow'), ('reflection', 'Reflection Shadow'), ('natural', 'Natural Shadow')], default='none', max_length=30)),
                ('dpi', models.IntegerField(default=72)),
                ('color_profile', models.CharField(default='sRGB', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='users.userprofile')),
            ],
        ),
    ]
