# Generated by Django 6.0.5 on 2026-05-21 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowtemplate',
            options={'ordering': ['-created_at']},
        ),
    ]
