# Generated by Django 6.0.5 on 2026-06-19 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(help_text='Max 10MB per file. Supported: JPG, PNG, WebP, GIF, SVG. Used in media library.', upload_to='media/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Auto-generated 300×300px thumbnail. Do not upload manually.', null=True, upload_to='media/thumbnails/%Y/%m/'),
        ),
    ]
