# Generated by Django 6.0.5 on 2026-06-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_alter_mediafile_file_alter_mediafile_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(help_text='Max 10MB per file. Supported formats: JPG, PNG, WebP, GIF, SVG for images; MP4, WebM for video; PDF, DOC, DOCX for documents. Uploaded and managed through the central media library.', upload_to='media/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Auto-generated 300×300px thumbnail. Do not upload manually. Created automatically when an image file is uploaded to the media library.', null=True, upload_to='media/thumbnails/%Y/%m/'),
        ),
    ]
