# Generated by Django 6.0.5 on 2026-06-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0003_alter_mediafile_file_alter_mediafile_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(help_text='General-purpose file upload for the central media library. Accepted formats: JPG, PNG, WebP, GIF, SVG (images); MP4, WebM (video); PDF, DOC, DOCX (documents). Maximum file size: 10MB. Images are used across the site — upload the highest resolution available and the system will serve appropriately.', upload_to='media/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Auto-generated 300×300px thumbnail. Do not upload manually. Created automatically from uploaded image files.', null=True, upload_to='media/thumbnails/%Y/%m/'),
        ),
    ]
