# Generated by Django 6.0.5 on 2026-06-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0004_alter_mediafile_file_alter_mediafile_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(help_text='General-purpose file upload. Accepted: JPG, PNG, WebP, GIF, SVG, MP4, WebM, PDF, DOC, DOCX. Max file size: 10MB. Upload highest resolution available.', upload_to='media/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Auto-generated 300x300px thumbnail. Do not upload manually — created automatically from uploaded images.', null=True, upload_to='media/thumbnails/%Y/%m/'),
        ),
    ]
