# Generated by Django 6.0.5 on 2026-06-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0005_alter_mediafile_file_alter_mediafile_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(help_text='Type: General-purpose file upload\nAccepted Formats: JPG, PNG, WebP, GIF, SVG, MP4, WebM, PDF, DOC, DOCX\nMax File Size: 10 MB\nDashboard thumbnail: 140 × 140 px crop, object-fit: cover\nRecommendation: Upload highest resolution available\n  — Files are stored at original resolution for admin use', upload_to='media/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Auto-generated 300 × 300 px thumbnail.\nDo NOT upload manually — created automatically from uploaded files.', null=True, upload_to='media/thumbnails/%Y/%m/'),
        ),
    ]
